### ISSUE TITLE
Add a link to Patternfly style guide

### ISSUE THREAD

**Issue by dayleparker** [redhat-documentation/supplementary-style-guide#116]
Another writer asked me about what to call a UI element today -- specifically the three dots that we call 'more options' in docs for the console.redhat.com apps. (Many designers/internal people call this the 'kebab' menu, but that's not optimal for localization or our customers.)

As it's a Patternfly UI element, I found my answer in that style guide: https://www.patternfly.org/v4/ux-writing/writing-for-all-audiences/#writing-for-all-abilities

So we don't duplicate all the good work in the Patternfly guide, what if we add a link to those guidelines and a sentence about what's documented there, so writers know where to look? Perhaps in this section or elsewhere: https://redhat-documentation.github.io/supplementary-style-guide/#user-interface-elements

Making this clear will help improve our consistency across various docs projects.

Thoughts?

**Comment by bergerhoffer** [comment]
@dayleparker Would you be interested in opening a PR to add this link to the Patternfly guide in? Or would you rather someone from the style council to do it? Thanks!
