### ISSUE TITLE
Guidelines for Organization Administrator / organization administrator  and Org Admin / org admin

### ISSUE THREAD

**Issue by spank50** [redhat-documentation/supplementary-style-guide#117]
In Red Hat customer-facing documentation (solutions, articles, CCS guides) the role of Organization Administrator appears several ways.

- Organization Administrator
- organization administrator
- Org Admin (short form)
- org admin (short form)

Because all the variations refer to the same role, we should use the same term for this role.

Customer Portal Examples:
https://access.redhat.com/solutions/17215
https://access.redhat.com/articles/1757953
https://access.redhat.com/articles/customer-service-accounts

Customer Documentation Examples:
Satellite
https://access.redhat.com/documentation/en-us/red_hat_satellite/5.8/html/getting_started_guide/chap-organizations

User Access/RBAC
https://access.redhat.com/documentation/en-us/red_hat_hybrid_cloud_console/2021/html/user_access_configuration_guide_for_role-based_access_control_rbac/assembly-rbac-procedures

IBM Style Guide suggests, "To distinguish whether a noun is a common noun or a proper noun, consider whether the noun refers to any one of many items (common noun) or whether it refers to the specific name of one item (proper noun)." 

Because this is the name of a single, specific role that each Red Hat corporate account must have, that suggests the answer is "Organization Administrator / Org Admin".

**Comment by bergerhoffer** [comment]
PR #118 added this to the style guide. Closing!
