### ISSUE TITLE
Guidelines for documenting CLI commands that require elevated privileges

### ISSUE THREAD

**Issue by bburt-rh** [redhat-documentation/supplementary-style-guide#121]
Currently, neither the _Supplementary Style Guide_ nor the _IBM Style Guide_ provide recommendations for how to handle sample CLI commands that require root privileges. A de facto standard practice seems to be to include a `$` or `#` at the beginning of the command to indicate the required permission level.

A few questions to consider (I'm sure that there are probably others that I'm not thinking of right of now): 

- Is including a `$` or `#` at the beginning of the command to indicate the required permission level always required? If so, is this method obvious enough to all of our users? 
- Should we always, sometimes, or never include `sudo` in the sample command if executing the command requires root privileges? 
- If elevated `sudo `privileges are required to perform tasks in a procedure, should this requirement always be listed in the Prerequisites section?

**Comment by bergerhoffer** [comment]
Good questions and I think that this would be good to add to the SSG.

I think that using # or $ to indicate root or regular user is helpful. But I also do think that it would be helpful to indicate early in the procedure or in the prerequisites that you'll need to be a root user. It's possible that someone might not know that the prompt indicates it, so an explicit mention in the prepreqs that root privs are required could be helpful. 

As for sudo, I would probably lean toward saying to use sudo when appropriate. I don't think that it will necessary be appropriate in all cases, so I don't think we'd want to recommend to update all commands that need to be run as root to use sudo instead.

I can't say that I document commands that require root very often, so would be interested in hearing what others think.

**Comment by libander** [comment]
This is a good question. I'd say sudo should be used whenever it's necessary to execute a command that requires elevated privileges. Arguably it sets a good example re using sudo over su. (It's also reasonable to assume someone in a position to be using our documentation is in the sudoers file, while they may not necessarily have root credentials.) From a user perspective, CLI samples are often copy & pasted into a terminal, having to figure out whether or not to add sudo first for each command would be frustrating.

**Comment by daobrien** [comment]
This is pretty well documented in the Red Hat Style Guide.

https://stylepedia.net/style/5.0/#idm46356813838448

**Comment by daobrien** [comment]
Yeah at some point CCS branched off and started doing their own thing, but I thought there's so much info in the RH Guide that seems to answer some of your questions you might as well make use of it. You might just need to tweak bits of it to suit your purpose. cheers.

**Comment by bburt-rh** [comment]
Draft content is ready for review and feedback at https://github.com/redhat-documentation/supplementary-style-guide/pull/139
