### ISSUE TITLE
Fix minor style issues and typos throughout the guide

### ISSUE THREAD

**Issue by inoxx03** [redhat-documentation/supplementary-style-guide#124]
This issue tracks minor style issues and typos identified in the guide that can be fixed separately from larger updates.

* https://redhat-documentation.github.io/supplementary-style-guide/index.html#appliance-console
	* set-up -> setup (set-up not recommended by IBM SG, we use _setup_ throughouth the SSG)

* https://redhat-documentation.github.io/supplementary-style-guide/index.html#composite-content-view
	* The abbreviation for Composite Content View should probably be "CCV", not "CVV"

**Comment by ndeevy** [comment]
#132 was merged for this issue. Closing.
