### ISSUE TITLE
Kubernetes Objects and Fields for Operator Documentation

### ISSUE THREAD

**Issue by oraNod** [redhat-documentation/supplementary-style-guide#13]
Terminology for describing objects and fields in Operator documentation should be consistent with Kubernetes wording.

Kubernetes objects: https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/ 
Custom resources: https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/

This issue suggests the following documentation conventions:

- Refer to custom resources by type, using bold text for the type name. For example, "...the **Infinispan** CR".
- Refer to user defined configuration options in custom resources as "fields" where necessary.
- Prefer to put focus on the task than describing fields. 

"Specify the number of nodes in the cluster with `spec.replicas` in your **Infinispan** CR." - Focuses more on task.
"Set a value for the `spec.replicas` field to define the number of nodes in the cluster." - Focuses more on the field (product).

**Comment by pwright** [comment]
just to note that existing doc often refers to 'parameter's as per https://docs.openshift.com/container-platform/4.5/networking/cluster-network-operator.html#nw-operator-cr_cluster-network-operator

**Comment by oraNod** [comment]
terminology should follow k8s doc conventions imo. that includes OpenShift docs.

**Comment by bergerhoffer** [comment]
Bold is only used for GUI items, so that should not be used for the custom resource type names. If we do decide that an object name needs markup (currently the OpenShift guidelines is to PascalCase without markup), then I think that monospace would be more appropriate.

Also note that the OpenShift docs team is currently reviewing how to refer to certain terminology (mostly capitalization) and is engaging the k8s community. The OpenShift docs team hopes to finalize our guidelines soon and we can share the outcome.

+1 for focusing more on tasks vs. fields.

Parameter vs field is a little more split and I'm not sure if we have set guidance on this, though it has been brought up. I tend to use field personally.

**Comment by oraNod** [comment]
Thanks for all the detail @bergerhoffer 

One note about bold for **Infinispan** CR. It is  in fact a GUI item (see the screengrab below). Infinispan is the name of the upstream project and I thought putting it in bold might help avoid a bit of confusion for users as well. At our next GA we'll have a **Cache** CR too, which is also a separate distinction to actual caches. TBH it's gotten a little wild and we're planning to revisit all of these things during the current planning phase. I'd be interested to hear any other thoughts. Cheers.

![image](https://user-images.githubusercontent.com/32749632/91837750-579c1700-ec44-11ea-8e9b-5b5657f49cbd.png)

**Comment by oraNod** [comment]
And I only just realized from the screenshot I pasted that it uses "fields". Nice.

**Comment by bergerhoffer** [comment]
Just updating to say that the OpenShift docs team has a proposal together to change the terminology reference guidance in our docs. Once it has been acked by all necessary stakeholders I will share that here.

**Comment by bergerhoffer** [comment]
PR #50 updates the OpenShift glossary items to address the recent terminology style updates per the OpenShift docs team.

This addresses (at least the glossary entries for) the first item suggested in the description. Any API object/resource should be marked up as a literal value in monospace. See the "API objects" glossary entry in that PR: https://github.com/redhat-documentation/supplementary-style-guide/blob/88b1256bb6603276dc35732e8cdc48ec1bec8817/supplementary_style_guide/glossary_terms_conventions/product_conventions/openshift.adoc#api-objects-noun

**Comment by oraNod** [comment]
monospace for the win

**Comment by oraNod** [comment]
@bergerhoffer Thanks for the style guidance. I'm going to close this issue now.
