### ISSUE TITLE
Master/slave entries in AMQ glossary

### ISSUE THREAD

**Issue by mportman12** [redhat-documentation/supplementary-style-guide#135]
In the AMQ section of the SSG glossary, there are multiple entries using [master/slave terminology](https://redhat-documentation.github.io/supplementary-style-guide/#master-slave-group):

- master-slave group
- master broker
- slave broker

Someone from AMQ should check whether we are still using this terminology in the documentation and update the SSG glossary if needed.

**Comment by bergerhoffer** [comment]
Hey @mportman12, thanks for pointing this out. We recently reached out to all products to look into adding/updating their product-specific terminology lists. Hopefully this will be addressed when that is done for AMQ.

@fbolton FYI on this. Can you check whether these terms are still correct for AMQ, or if they need to be updated?

**Comment by bergerhoffer** [comment]
I emailed Fintan this morning and got this reponse:

> The "master" and "slave" terms are still in use in Broker. See for example this guide:
https://access.redhat.com/documentation/en-us/red_hat_amq/2021.q3/html-single/configuring_amq_broker/index
> This is a tricky one to fix, because the terms are embedded in the code.

So it looks like these terms are still being used, and it's not a change docs can make until the product makes the change first. 

Closing this issue.
