### ISSUE TITLE
Add terminology for Red Hat Insights

### ISSUE THREAD

**Issue by inoxx03** [redhat-documentation/supplementary-style-guide#142]
Product-specific terms related to Red Hat Insights:

The following names designate the names of products that are part of The Red Hat insights offering 

* Advisor - manages configuration issues that affect availability, stability, performance and security
* Compliance-  assess and monitor the compliance of RHEL systems with SCAP security policies
* Drift - provides comparison of your systems' configuration over time to track and analyze changes
* Patch - view all all Red Hat advisories and patch any system with or more advisories
* Policies - notification of changes to systems or pot
* Resource Optimization - monitor your public cloud systems and improve waste management and rightsizing 
* Vulnerability - assess and monitor of RHEL infrastructure exposure to common vulnerabilities and exposures

The following terms have been highlighted as relevant to Red Hat Insights, but are not product-specific. 
I would recommend that we add them under hte general glossary section
* CVE- common vulnerabilities and exposures
* RBAC - role based access control 
* SCAP - security content automation protocol
* PCP - Performance Co-Pilot [Documented in RHEL](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/performance_tuning_guide/ch-performance-co-pilot)

**Comment by emarcusRH** [comment]
> Product-specific terms related to Red Hat Insights:
> 
> The following names designate the names of products that are part of The Red Hat insights offering
> 
>     * Advisor - manages configuration issues that affect availability, stability, performance and security
> 
>     * Compliance-  assess and monitor the compliance of RHEL systems with SCAP security policies
> 
>     * Drift - provides comparison of your systems' configuration over time to track and analyze changes
> 
>     * Patch - view all all Red Hat advisories and patch any system with or more advisories
> 
>     * Policies - notification of changes to systems or pot
> 
>     * Resource Optimization - monitor your public cloud systems and improve waste management and rightsizing
> 
>     * Vulnerability - assess and monitor of RHEL infrastructure exposure to common vulnerabilities and exposures
> 
> 
> The following terms have been highlighted as relevant to Red Hat Insights, but are not product-specific. I would recommend that we add them under hte general glossary section
> 
>     * CVE- common vulnerabilities and exposures
> 
>     * RBAC - role based access control
> 
>     * SCAP - security content automation protocol
> 
>     * PCP - Performance Co-Pilot [Documented in RHEL](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/performance_tuning_guide/ch-performance-co-pilot)

I am not an expert on Insights, but I did a little bit of research on the topic in order to link it to the RHV Administration Guide
- **Red Hat Insights** is the product
- all of the names listed above are components or services within Red Hat Insights, and also names of menu items or tabs in the Dashboard -  see [Insights Dashboard](https://console.redhat.com/insights/overview#SIDs=&tags=)
and see also - titles in [Red Hat Insights documentation](https://access.redhat.com/documentation/en-us/red_hat_insights/2021)

**Comment by Amrita42** [comment]
@inoxx03 is there some guidance or ref on ` terms that have been highlighted as relevant to Red Hat Insights`

**Comment by bergerhoffer** [comment]
@inoxx03 can you confirm whether we still need to add these terms, and if so, raise a PR? Or see if someone from the Insights team can raise one?

**Comment by Amrita42** [comment]
I need some clarity on the query that I have raised to take this issue further (into a PR). I am ok with someone else taking this up too :)

**Comment by bburt-rh** [comment]
@Amrita42 Do you have any further details you can provide about what info we need to move forward with this issue? Do you know who might have knowledge to help us?

**Comment by bergerhoffer** [comment]
@inoxx03 Is this something that still needs to be addressed? If so, can you please provide a PR or details so that someone else can open a PR? Or if not, can this issue be closed?
