### ISSUE TITLE
Code blocks and technical elements (Compare current IBM Style Guide to our guide)

### ISSUE THREAD

**Issue by IngridT1** [redhat-documentation/supplementary-style-guide#143]
We have a fair amount of guidance around code blocks. I was just reviewing similar information in the IBM Style Guide with members of the IBM Style Council. It looks like they have more guidance than I realized. We probably need someone more technical than I am to check the two sources against each other. 

**IBM Style Guide versus Red Hat Supplementary Style guide.** We have some overlap, but we also have named our guidelines differently. That may be why we couldn’t find the info in the IBM SG in the first place. 

- [Technical elements](https://www.ibm.com/docs/en/ibm-style?topic=technical-elements) (IBM Style guide)

_[Code and command examples](https://www.ibm.com/docs/en/ibm-style?topic=elements-code-command-examples)
[Command line data entry](https://www.ibm.com/docs/en/ibm-style?topic=elements-command-line-data-entry)
[Command syntax](https://www.ibm.com/docs/en/ibm-style?topic=elements-command-syntax)
[Commands](https://www.ibm.com/docs/en/ibm-style?topic=elements-commands)
[Files and directories](https://www.ibm.com/docs/en/ibm-style?topic=elements-files-directories)
[Variables](https://www.ibm.com/docs/en/ibm-style?topic=elements-programming#variables)_

- Red Hat supplementary style guide

_[Code examples](https://redhat-documentation.github.io/supplementary-style-guide/#code-examples)
[User-replaced variables](https://redhat-documentation.github.io/supplementary-style-guide/#user-replaced-values)
[User-replaced variables for XML](https://redhat-documentation.github.io/supplementary-style-guide/#user-replaced-values-xml)_

@bergerhoffer said that she could look at this and do a comparison.

**Comment by Srivaralakshmi** [comment]
@bergerhoffer Thanks for taking this up :)

Any updates on the progress made so far? Thanks!

**Comment by mportman12** [comment]
@bergerhoffer Any updates on this issue?

**Comment by Amrita42** [comment]
@bergerhoffer Are there any updates on this issue ?
