### ISSUE TITLE
Grammatical errors in example deprecation notice and removal notice doc texts

### ISSUE THREAD

**Issue by bburt-rh** [redhat-documentation/supplementary-style-guide#144]
In the "Release notes" section of the style guide in the "Deprecated functionality" sub-section, two example texts are provided, both of which contain ungrammatical sentences:

- `Bug fixes and support is provided through the end of a future life cycle but Red Hat do not implement new feature enhancements.`

should read `Bug fixes and support are provided through the end of a future life cycle, but Red Hat will not implement new feature enhancements.`

- `Bug fixes and support are provided through the end of the RHOSP 15 life cycle but Red Hat do not implement new feature enhancements.`

should read `Bug fixes and support are provided through the end of the RHOSP 15 life cycle, but Red Hat will not implement new feature enhancements.`

Also in both the "Deprecation notice" and "Removal notice" templates, the sentence `After which, no new feature enhancements are made.` seems like a sentence fragment to me despite the comma usage. At the very least, it seems like an awkward construction to my ears. Maybe replace `After which` with `After this point` and `are made` with `will be made`.

I can make these changes if others agree that these are legitimate issues.

**Comment by bergerhoffer** [comment]
I agree with the suggested modifications to the first two bullets.

And +1 to there being room for improvement with "After which, no new feature enhancements are made." 

I'm guessing the "are" was to try to get rid of the future tense "will". But I don't have a strong preference on whether we need to avoid it here or not. It might sound better with the "are" if we rearrange like this:

```
No new feature enhancements are made after this time.
```

But if we want to keep "After" first, then I'm fine with the "will". Others might have stronger opinions on this though.

**Additional request:** We follow ISG's "lifecycle" one word. Would you mind fixing the instances of two words that you see here? There might be a few other instances in the SSG too that could also be updated
