### ISSUE TITLE
Add guidance for referring to changes that apply from a particular version onward

### ISSUE THREAD

**Issue by inoxx03** [redhat-documentation/supplementary-style-guide#145]
This topic has been suggested by @oranod and @sangeetaraghu
We should consider providing guidance on how to refer to changes to a product that apply form a particular version onward.

There are multiple ways that this can be expressed, and I can see them all over our docs sets. For example
"{FeatureName} is available in {ProductName} version X.Y or later."
"{FeatureName} is available in {ProductName} as of version X.Y."
"{FeatureName} is available in {ProductName} from version X.Y onward."

We should consider recommending a standard way of phrasing this type of statements in our documentation.

**Comment by emarcusRH** [comment]
IBM Style Guide: References to earlier or later versions
To state a requirement that includes earlier or later versions of a product, use the phrases **or earlier** to indicate earlier versions
and **or later** to indicate subsequent versions.

**Comment by oraNod** [comment]
@bergerhoffer and @emarcusRH Thanks, I believe we had discussed the IBM style guide conventions. It seems to me this issue is missing some nuances from the conversation we had but I'm unsure if it's worth going into too much detail. I'm happy enough to just close it. Thanks.
