### ISSUE TITLE
Consider providing guidance on the usage of Java-specific terminology

### ISSUE THREAD

**Issue by inoxx03** [redhat-documentation/supplementary-style-guide#154]
Developer-oriented content related to Java applications relies on language specific terms.

For example, when discussing exception handling in Java, developers use the verb _throw_ when referring to a program encountering an exception state.
Similarly, the verb _catch_ refers to handling an exception state programmatically within the application code.
These terms actually mirror the Java language keywords (`throw` and `catch`, respectively) that are used within the code for these purposes.

Several peers have pointed out that these terms are not typical and might not be understood by a large part of our audience, and have called for them to be replaced by non-language specific equivalents in product documentation.

We should consider providing guidance in the SSG around the usage of these terms, if we agree that the guidance that the ISG already provides around the use for these terms is not sufficient for the purposes of product documentation.

**Comment by inoxx03** [comment]
Considerations:

* Even though these terms are specific to Java, even very junior developers working within the Java ecosystem are extremely likely to be familiar with their meaning. (If such developers are )
* Some suggested alternative terms such as using `return` instead of `throw` are IMHO not suitable for Java, because `return` is another keyword used in Java code.
* _Throwing an exception_ an exception and _returning an error message_ are seemingly equivalent phrases in general. In Java, they have their own different technical meanings.
* Some well-known resources on the Java language (including the Java documentation set by Oracle) use  _throw_ and _catch_ as standard Java terminology in their documentation. Use of these terms is also prevalent in articles and blogs related to Java development

**Comment by bergerhoffer** [comment]
@inoxx03 I would agree that the terms `throw` and `catch` are correct in the context of Java. I would not advise to make any changes to the guidance of these terms in the SSG. `throw` and `catch` are actual Java code keywords. 

To me, it sounds like you're raising this issue so that we can discuss more broadly to see if these words should be changed, but you don't personally agree that they should be changed. Is that correct?

If so, then my vote would be to not change the terms or add any different guidance in the SSG, and instead follow the ISG, which deems these terms as appropriate.

@redhat-documentation/ccs-style-council other thoughts?

**Comment by inoxx03** [comment]
@bergerhoffer Yes, I believe that these terms should not be changed or replaced by alternative terms. As you say, in the context of Java `throw` and `catch` are terms that carry a specialized and reserved meaning. As such, they are not jargon, colloquialisms, or an example of "developerese", and their use in documentation (when referring to Java) is not bad style. If anything, I believe replacing these terms with any other terms (in the same context) would make documentation less accurate.

My initial impulse for creating this issue came from a discussion I've had with our writers, some of whom have raised the point that these terms don't sound "right" to them. However, the ISG provides ample clarification about when it is appropriate to use these terms in documentation, and I think our best course of action in this case is to follow the Guidance given by the ISG.
I believe we should not change these terms, but at the same time I want to hear what other style council members have to say about this.

If we all concur that this is a "non-issue" of the SSG, I will be happy to close it.

**Comment by inoxx03** [comment]
2/23/22 - After raising this point with the SSG group in our monthly meeting, we have agreed to defer to the IBM Style guide for guidance on the usage of the terms `catch` and `throw` in the context of Java programming.

I am closing this as a non-issue.
