### ISSUE TITLE
Request change to Graphical interfaces topic

### ISSUE THREAD

**Issue by jlprevatt** [redhat-documentation/supplementary-style-guide#16]
For file: supplementary-style-guide/supplementary_style_guide/style_guidelines/graphical-interfaces.adoc

In this topic, the "User interface elements" section contains the following sentence:
"Bold all graphical user interface elements, including, but not limited to, menu names, menu items, button names, and _dialog window names_."

I am requesting a change for the phrase "dialog window" to something like "windows, wizard pages, and dialog boxes" or something similar. A "dialog window" mixes the names of two different graphical user interface elements.

A dialog box (not dialog) is a different than a window. In the definition that I am most familiar with, a dialog box appears inside of an application window when you do a certain action and frequently asks for a response that you must give before continuing (or you can cancel the dialog box and that cancels the action). A dialog box contains no other navigation--you can either accept or reject the question or you can cancel it with the X. A dialog box might not have a name, just the content of the question/decision. (Caveat: More recently, I have seen some UX information that defines the "must make a choice before continuing" as a *modal* dialog box.)

A window is the graphical representation of an application, and it might display one or more dialog boxes inside of it as you do various actions. A window contains navigation, such as scroll bars, menus, etc.

**Comment by bergerhoffer** [comment]
@jlprevatt Thanks for raising this - I will open a PR to fix.

**Comment by bergerhoffer** [comment]
@jlprevatt Here is the PR if you can please review: #17.

**Comment by bergerhoffer** [comment]
Closing as PR #17 has been merged to address this issue.
