### ISSUE TITLE
Issue for collecting examples of introductions/abstracts (add yours)

### ISSUE THREAD

**Issue by stoobie** [redhat-documentation/supplementary-style-guide#168]
_This issue is a follow-up to #75._

#### This issue is for collecting examples of introductory sentences in preparation for a PR to add this information to the style guide.

***Particularly, we're looking for good intro paragraphs where it's difficult to come up with something useful to say that doesn't just repeat the heading.***

## The details:

After meeting with stakeholders in the Mod Docs team, we decided:

- What is primarily missing is a collection of useful examples of introductions.
- Regarding where to put this information, we discussed the following options:
  - the Modular Documentation Reference Guide
  - the Supplementary style guide
  - other internal reference, such as the intranet
  - a Red Hat blog
- We decided that the style guide is the most appropriate place to put this information. One of the considerations is that the information be publicly available, and because this information isn't strictly tied to modular documentation, the style guide is the best place.

**Comment by IngridT1** [comment]
Lorena Burcher and I have begun a Google doc with several good examples. It's a work in progress, but this is what we have so far.
https://docs.google.com/document/d/1CCg0svB4-cNjaqTAtcN9CeU-WiajivHBm7lmIgxQ4Eo/edit#

**Comment by Srivaralakshmi** [comment]
Hi @IngridT1, Thanks to you and Lorena for the work on the examples. Just checking with you for updates on the progress.

**Comment by mportman12** [comment]
@IngridT1 Following up on this. Do you and Lorena have any updates?

**Comment by IngridT1** [comment]
Not really, but your ping has put it back on our radar.

**Comment by bergerhoffer** [comment]
Updating to say that there is a cross-product findability effort that is working on an entry to the SSG for this :tada: Thank you to @bgaydosrh / Lorena / @IngridT1 !

**Comment by bburt-rh** [comment]
@bgaydosrh @IngridT1 - When you get a chance, could one of you please post a status and tentative timeline for resolution of this issue? Thanks!

**Comment by bgaydosrh** [comment]
Yes @bburt-rh - I have contacted Lorena Burcher and will update you on when the entry will be ready for submission. Thanks for your patience.....

**Comment by bgaydosrh** [comment]
Lorena will post an update to this issue soon, thanks again.

**Comment by bergerhoffer** [comment]
@lburcher7 Just wanted to check and see if there were any updates to getting the draft content about intro content into the SSG?

**Comment by lburcher7** [comment]
@bergerhoffer I just closed a few last comments from the google doc with the entry. I do need a bit a of help opening a PR for this since I'm not used to. @mportman12 or @bredamc, could one of you help me? I could also ask in the Style Council chat... Thank you!

**Comment by mportman12** [comment]
@lburcher7 The [Contributing guide](https://github.com/redhat-documentation/supplementary-style-guide/blob/main/CONTRIBUTING.md) walks through the basic steps, but it assumes you're familiar with Git already. If you've never used Git before, probably the easiest thing would be for me to create the PR for you.

**Comment by lburcher7** [comment]
Thanks for the link, @mportman12. I am familiar with Git, but don't use it often enough. I am going to attempt to create this PR and will let you know if I run into problems. Ingrid and I are closing the last 2 comments in the google doc.

**Comment by lburcher7** [comment]
I created a PR for this entry: https://github.com/redhat-documentation/supplementary-style-guide/pull/301
