### ISSUE TITLE
Guidance on AMD64 vs x86_64

### ISSUE THREAD

**Issue by max-cx** [redhat-documentation/supplementary-style-guide#171]
The following guidance is incorrect and has to be changed:

![image](https://user-images.githubusercontent.com/78564304/158784899-f972a9cd-0114-465d-ba2f-df77a4d28d82.png)

`x86_64` and `AMD64` are not interchangeable. `x86_64` covers both `Intel 64` and `AMD64`. To rewrite `x86_64` as `AMD64` means telling readers (including those that use `Intel 64` for Red Hat products) that `Intel 64` does not exist and is not supported. (In other words, this guidance says that using the word `car` is a mistake and that we must replace `car` with `BMW`.)

OpenShift docs (and many, many package names for Linux distros) refer to `x86_64`: https://docs.openshift.com/container-platform/4.10/installing/installing-preparing.html

More info below:
https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures#64-bit_(x86-64)
https://en.wikipedia.org/wiki/X86
https://www.pcmag.com/encyclopedia/term/x64
https://www.intel.com/content/www/us/en/architecture-and-technology/microarchitecture/intel-64-architecture-general.html
https://www.pcmag.com/encyclopedia/term/amd64 (edited) 

![image](https://user-images.githubusercontent.com/78564304/158636550-13da6904-40a1-4173-b81c-0d7eda79ebdf.png)
(source: https://www.intel.com/content/www/us/en/architecture-and-technology/microarchitecture/intel-64-architecture-general.html)

`Intel 64` is explicitly supported on RHEL:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_installation/installing-rhel-on-adm64-intel-64-and-64-bit-arm
`x86_64` overall is supported on Fedora:
https://getfedora.org/en/coreos?stream=stable

**Comment by bergerhoffer** [comment]
@max-cx I see how this could look like it, but I don't think that this entry is trying to tell you to replace all instances of "x86_64" with "AMD64". The definition itself is saying that it is "an implementation" of x86_64. Not the only one.

However, I agree that we can make an improvement here to make it clearer. So here would be my suggestion:

* We add an entry for "Intel 64" (or whatever the proper way to write it is) and say that it is "an implementation..."
* We add an entry for "x86_64" saying not to use it, and to instead use AMD64 or Intel 64 (when you mean one specifically), or call out both if you need to talk about it generically.

wdyt?

**Comment by Srivaralakshmi** [comment]
Hi, @max-cx! Thanks for raising this issue. Can you please respond to @bergerhoffer' s suggestion?

Hi @redhat-documentation/ccs-style-council, this issue still needs more discussion; those with input please add to this GitHub issue thread to see if we can come to an agreement on what action to take. Please share your thoughts when you have free time 👍. Thanks!

**Comment by mportman12** [comment]
+1 for adding entries for Intel 64 and for x86_64. However, I think there's a larger discussion about what the correct terms for these architectures are. For example, should we recommend `Intel 64`, `Intel64`, `Intel 64-bit architecture` or `64-bit Intel architecture`? All of these are used inconsistently in RHEL documentation, at least.

**Comment by stoobie** [comment]
Here is Intel's guidance:

https://www.intel.com/content/www/us/en/architecture-and-technology/microarchitecture/intel-64-architecture-general.html

**Comment by Srivaralakshmi** [comment]
Hi @max-cx! Thanks for your inputs.

Hi https://github.com/orgs/redhat-documentation/teams/ccs-style-council, WDYT? Please let us know your thoughts. Thanks!

**Comment by mportman12** [comment]
I agree with @max-cx that we should label `x86_64` as "Use with caution" instead of outright prohibiting. To borrow a recent example from my own documentation, I needed to use `x86_64` for a repository ID:
![Screenshot from 2022-05-19 13-54-26](https://user-images.githubusercontent.com/74915975/169366233-3f34e5bd-349f-46fd-bcfd-3705ee556ab2.png)

**Comment by bergerhoffer** [comment]
We've talked about this a bit at some of the SSG meetings. And we agree that we need some clarification, but that we need some assistance from some more SMEs (across products probably). Not sure if anyone has any good SME contacts that they can reach out to for some more input?

**Comment by bburt-rh** [comment]
@bergerhoffer Maybe put this on the next SSG agenda to see how best to find a SME to help us out?

**Comment by daobrien** [comment]
Because this appears in all three style guides, it should probably be expanded to include reps from all those guides. Deciding on a "solution" for just this guide and not incorporating it into the other two is very likely to cause confusion. Thanks

**Comment by kelbrown20** [comment]
@bergerhoffer @bburt-rh Myself and some SMEs from multi-arch and arm are working on a best practices guide on the use cases for both x86_64 vs amd64 and arm64 vs aarch64

**Comment by bburt-rh** [comment]
Thank you, @kelbrown20!

**Comment by pwright** [comment]
Having spoken to @kelbrown20 I'm happy with this change.

**Comment by mportman12** [comment]
Met with @kelbrown20 who has put together a draft of glossary entries after discussing with SMEs. Long story short, there are specific use cases for most versions of the architecture terminology, and her glossary entries explain these use cases in detail. Kelly has volunteered to create a PR for this.

**Comment by Srivaralakshmi** [comment]
This is the [PR ](https://github.com/redhat-documentation/supplementary-style-guide/pull/295) that @kelbrown20 is working on to resolve this issue. Thanks a lot, Kelly for your time and work. Appreciate it!

**Comment by Srivaralakshmi** [comment]
#295

**Comment by mportman12** [comment]
PR has been merged. Closing ticket.
