### ISSUE TITLE
Remove references to cost from the documentation. 

### ISSUE THREAD

**Issue by EricPonvelle** [redhat-documentation/supplementary-style-guide#186]
In the ISG, the term "free" is to be avoided with regards to costs, and instead, a phrase like "no initial cost" was suggested. When following up on the proper replacement, the consensus was that we should purge any references to cost at all. Costs should purely stay with other channels that can change faster than documentation.

I propose we add a section to the SSG that states that we do not mention costs (even if it's free) in our documentation.

**Comment by porueesq** [comment]
Referring to the IBM Style Guide:
![image](https://user-images.githubusercontent.com/43811485/174316075-547cdc4e-ca1d-4646-8a30-aa08015ffcf4.png)


Additionally, _free_ according to the FSF [0]:

> Free software is software that gives you the user the freedom to share, study and modify it. We call this free software because the user is free. 

With these two examples, we can see that the term _free_ is semantically overloaded.

@redhat-documentation/ccs-style-council Can we create a PR for this? 

[0] https://www.fsf.org/about/what-is-free-software

**Comment by bergerhoffer** [comment]
@EricPonvelle the SSG council agreed that we should leave out cost references in product documentation. Would you be up for submitting a PR to add a new section for this to our style guidelines? If so, we can provide assistance with how/where if needed. Thanks!

**Comment by bergerhoffer** [comment]
Closing, since PR #214 added this in to the SSG.
