### ISSUE TITLE
Capturing issues found during the reorg eval: AMQ

### ISSUE THREAD

**Issue by mportman12** [redhat-documentation/supplementary-style-guide#188]
Capturing AMQ issues noticed during the reorg. Need to follow up after the reorg:

- [ ]  Review AMQ terms for any that say "In Red Hat AMQ" but might be better as something more generic like "In messaging" or "In JMS" or something. For example, "queue", "producer", "consumer", etc. Note that "destination" currently uses "In JMS".

**Comment by bburt-rh** [comment]
@joaedwar The re-org is complete. When you get a chance, could you please let us know the status of your work on this issue? Thank you!

**Comment by bergerhoffer** [comment]
I am closing this issue. Some of these terms could potentially be generic, but this isn't a critical update.
