### ISSUE TITLE
Capturing issues found during the reorg eval: Ceph

### ISSUE THREAD

**Issue by mportman12** [redhat-documentation/supplementary-style-guide#189]
Capturing Ceph issues noticed during the reorg. Need to follow up after the reorg:

- [ ]  Evaluate Ceph terms to see if any are general enough to stand alone, or to be removed completely. (bucket, etc). Also there is a reference to version 1.3 that should be checked.
- [x] Fix broken link in Ceph's "pool" entry.

**Comment by bergerhoffer** [comment]
Broken link was fixed via #244. First issue isn't critical. Closing!
