### ISSUE TITLE
Capturing issues found during the reorg eval: Foreman

### ISSUE THREAD

**Issue by mportman12** [redhat-documentation/supplementary-style-guide#190]
Capturing Foreman issues noticed during the reorg. Need to follow up after the reorg:

- [ ] The Foreman entry mentions a BZ to get a UI element changed, but the BZ was closed as WONTFIX. If it's still an issue, remove the reference to the BZ. If it's not still an issue, remove the guidance on it all (last 3 sentences)

**Comment by bergerhoffer** [comment]
Per Marie:

> As of now, downstream uses only "Satellite", so you can safely remove that part of the description related to RH Virt.
> So this text can be removed: "In Red Hat Virtualization, use "Foreman/Satellite" when referring 
directly to the UI element. Do not use "Foreman" or "Foreman/Satellite" 
to refer to Red Hat Satellite in other cases. A bug is open to get this 
element changed to Satellite."

@redhat-documentation/ccs-style-council Here's an easy one if anyone has a minute to submit a PR to remove the above text from the "Foreman" entry.
