### ISSUE TITLE
Capturing issues found during the reorg eval: Fuse

### ISSUE THREAD

**Issue by mportman12** [redhat-documentation/supplementary-style-guide#191]
Capturing Fuse issues noticed during the reorg. Need to follow up after the reorg:

- [ ]  Need to make changes to the Fuse terms that were suggested in the spreadsheet. This includes things like removing a few entries, renaming items, etc.

**Comment by bredamc** [comment]
@bergerhoffer I can take this one -- can you please assign it to me? Thanks :)

**Comment by bredamc** [comment]
Apologies for the delay -- I will work on this issue when the master branch has been renamed to main.

**Comment by bredamc** [comment]
PR: https://github.com/redhat-documentation/supplementary-style-guide/pull/231

**Comment by bredamc** [comment]
PR 231 has been merged :)
