### ISSUE TITLE
Capturing issues found during the reorg eval: General

### ISSUE THREAD

**Issue by mportman12** [redhat-documentation/supplementary-style-guide#192]
Capturing general and minor issues noticed during the reorg. Need to follow up after the reorg:

- [x]  SSO terms are missing the (\<class>) designation
- [x] OCS terms are missing the yes/no/with caution icons
- [x] The link to the Microsoft Azure glossary is broken. I think it should probably be changed to https://docs.microsoft.com/en-us/azure/azure-glossary-cloud-terminology
- [x]  Terms that have two or more descriptions should use the same syntax for the 1/2/n. Some places use (1) and (2), others use 1) and 2). Pick one and use it consistently
- [ ]  ~~If we keep the ^ OpenStack services entry, consider whether it's okay as bullets or not. I thought we didn't want to use bullets because of systems like Vale that might be parsing the entries. Looks like the Operator entry is complex as well.~~
- [x] Fix "behaviour" to "behavior"
- [x]  Remove the outdated terms "OpenShift master" and "Kubernetes master". Or change them to do not use.
- [x]  The "Use it" field for "OpenShift" says "yes, as described above". This should either be changed to "yes" or "with caution". Same for the "user name" field
- [ ]  BxMS product name has changed and should be updated throughout its terms. Ping @sterobin for help - some of the component names changed too.

**Comment by bergerhoffer** [comment]
Fixed first batch of issues in PR #230.

**Comment by Srivaralakshmi** [comment]
@bergerhoffer Thanks for the awesome work on this issue so far. Any updates/progress on this issue?

**Comment by bredamc** [comment]
@bergerhoffer Is it you or someone else who will tackle the final two items on this list?

**Comment by bergerhoffer** [comment]
I think we can leave out the OpenStack services entry. And not worry about if descriptions have complex entries. If that becomes an issue, we can re-evaluate then. Crossing that one off.

I will see if I can find a contact from business automation to help with updating the BxMS entries properly.

**Comment by bergerhoffer** [comment]
Have reached out and @emmurphy1 has agreed to help us with what updates we need to make for the BxMS mentions.

**Comment by bburt-rh** [comment]
@bergerhoffer Where does this one stand at the moment?

**Comment by bergerhoffer** [comment]
Closing this one out since it's been sitting open for so long. 

All items have been addressed - the last one is the BxMS one, which has a PR opened for it.
