### ISSUE TITLE
Capturing issues found during the reorg eval: IdM

### ISSUE THREAD

**Issue by mportman12** [redhat-documentation/supplementary-style-guide#193]
Capturing IdM issues noticed during the reorg. Need to follow up after the reorg:

- [ ] Certificate authorities description goes into probably too much specifics to Red Hat Identity Management for the SSG. Probably remove everything except the first sentence. Actually... there are several general ones like this. Review these other entries as well: Apache web server, cross-forest trust, domain controller, Kerberos protocol, Kerberos realm, Key Distribution Center, POSIX, web server (Check the RHEL tab of spreadsheet, possibly more). Determine if we want to just remove the IDM-specific pieces, or make them a 1) and 2) situation.

**Comment by ndeevy** [comment]
Thought I could get to this but am swamped :-< so I'm removing myself in case another helpful soul can.

**Comment by mportman12** [comment]
@Srivaralakshmi I can take this.

**Comment by Srivaralakshmi** [comment]
@mportman12 Any progress on this one so far? Just checking : )

**Comment by mportman12** [comment]
Closing issue because PR is merged.
