### ISSUE TITLE
Use nbsp to keep the words "Red" and "Hat" together

### ISSUE THREAD

**Issue by nalhadef** [redhat-documentation/supplementary-style-guide#196]
Currently, the IBM Style Guide and the Red Hat Supplemental Style Guide do not advise us to separate "Red" and "Hat" with a non-breaking space. Use of a NBSP keeps both halves of our name together on one line, avoiding possible weakening of our trademark.

Shall we add this to one of the style guides (This must have been in one of the guides or peer review documents at one point. I'm not sure how I'd be aware of it otherwise.)

**Comment by mportman12** [comment]
This blog post from 2016 also mentions a requirement to use non-breaking spaces between products and version numbers (e.g. RHEL 8).
https://source.redhat.com/groups/public/curriculum-team/jb421/mw421_wiki/common_spelling_and_grammar_errors

**Comment by daobrien** [comment]
https://stylepedia.net/style/5.1/#nonbreaking-spaces covers this. Also between values and units (64{nbsp}GB). There's probably some other cases but I can't think what they are off the top of my head.

Just FYI that blog post is really old and probably contains outdated material.

**Comment by rolfedh** [comment]
See thread here https://coreos.slack.com/archives/C0218RXJK5E/p1657098402656789

**Comment by bergerhoffer** [comment]
This suggestion makes sense to me, but I know that we do not do this on OpenShift (and I don't think we did when I was on EAP).

Does anyone work on product docs in CCS that uses a {nbsp} in between all instances of "Red" and "Hat"? I'd like to know how many currently do, and if so, how they do it consistently (attribute?).

**Comment by nalhadef** [comment]
Hi, Andrea.

We use Red<nbsp>Hat in the CPaaS documentation. We type it in each time. An
attribute is a good idea, though!

**Comment by bergerhoffer** [comment]
Thanks @nalhadef! Is it actually `Red{nbsp}Hat` (for AsciiDoc)?

**Comment by nalhadef** [comment]
Yeah. I do better with autofill! Thanks!

**Comment by bergerhoffer** [comment]
Discussed this at the 30 November SSG meeting.

Agreement that we should add guidance for nbsp between "Red" and "Hat". If we need to also add guidance for anything else (like product names, etc.), that can be done later.

@redhat-documentation/ccs-style-council Any volunteers to open a PR for this new guidance?

**Comment by mportman12** [comment]
Created PR: https://github.com/redhat-documentation/supplementary-style-guide/pull/270
