### ISSUE TITLE
Can we revisit the word-usage guidance on plugin (noun)? 

### ISSUE THREAD

**Issue by michelle-purcell** [redhat-documentation/supplementary-style-guide#213]
![image](https://user-images.githubusercontent.com/92924207/187479099-71ee86d8-b87e-4970-99d6-9d9c3cb3fe58.png)

**Problem:** 

“Plugin” and “plug-in” (noun) are used synonymously in published technical documentation online.

Red Hat and IBM styles favor the hyphenated form, whereas many of our other integrated technologies and developer-type community projects prefer 'plugin' (see google example below). This creates a lot of churn and pushback in our upstream communities. Many developers prefer 'plugin' without the hyphen. 

Our current style guide advice to use 'plug-in' instead of 'plugin' was rejected by our Quarkus upstream project community engineers. Our developers prefer 'plugin'. This creates challenges and lots of churn for Red Hat writers who have to convert 'plugin' (used widely upstream) to 'plug-in' (required downstream), especially as we move to an upstream-first content development model. It's doable but our time could be better spent on other content quality enhancements.

While 'plug-in' is said to be more grammatically correct, according to the Merriam-Webster dictionary, it also seems to be seen as a more formal and 'old-fashioned' form of the word. Is it time to relax the rule, especially for developer-type content, where the plugin tends to trump plug-in? Could we revisit the word usage for 'plug-in' with the IBM Style council?

**Example:**
https://developers.google.com/style/word-list#letter-p

![image](https://user-images.githubusercontent.com/92924207/187473279-7f24b16d-0499-4eed-82a1-7ec9ce2e84da.png)

**Comment by lahinson** [comment]
@michelle-purcell The co-chairs of the IBM Style Council meet periodically with a few writers and editors from Red Hat to discuss issues like this one. I think the next meeting is 9 September. Would you like me to add this item to the agenda? I can also ask for an invitation for you to join, if you like.

**Comment by michelle-purcell** [comment]
@lahinson - Thank you, Laura. It would be great if you could raise this. I will try to attend the discussion if I can. Do let me know if you need any further information or examples. :-)

**Comment by bredamc** [comment]
@michelle-purcell As a workaround, you could replace the problem word with a {plugin} attribute, and define that attribute to have the value "plugin" upstream and "plug-in" downstream?

**Comment by michelle-purcell** [comment]
@bredamc - Thank you Breda for the great idea. 

Before we go down the route of attributes, we'd like to see if there's a simpler way, more so for our external community contributors who are not asciidoc tech writers and might be discouraged to contribute to the upstream docs if they see lots of different attributes for word usage. We already think we will have many attributes for product and platform names, versions, paths etc.

Also, from a reader perspective, we are wondering about the user experience of seeing the variations when switching from upstream to downstream, especially when several developers have already made it clear that they don't like 'plug-in'. Maybe it's not a big deal for most...  Thanks again!

**Comment by sheilamjones** [comment]
Thanks @michelle-purcell for raising this. +1 to your comments that though 'plug-in' is said to be the more grammatically correct form, it also seems to be the more  'old-fashioned' form of the word. I found similar discussion online with similar conclusions, in that "plug-in" is still listed as more grammatically correct form but that usage has evolved to "plugin" and this is more widely used particularly in more developer-oriented communities.

Example of similar discussions online: 
https://grammarhow.com/plugin-plug-in-or-plug-in/
https://github.com/MicrosoftDocs/microsoft-style-guide/issues/242

**Comment by michelle-purcell** [comment]
@sheilamjones - Thank you Sheila. Great example.

**Comment by michelle-purcell** [comment]
Another good discussion on the topic from one of our lead SMEs: https://grammarhow.com/plugin-plug-in-or-plug-in/

**Comment by lahinson** [comment]
@michelle-purcell In the IBM Style/Red Hat meeting this morning, I brought up your question about plug-in. The IBM Style council co-chairs couldn't think of a reason to continue hyphenating the term, but they are bringing the issue to the rest of the council, including the IBM Terminologist, to find out whether there's a good reason to keep the hyphen. I'll keep you posted as I know more.

**Comment by michelle-purcell** [comment]
@lahinson @bergerhoffer - Don't know how I missed this update?!! 
That is great news. Thank you so much for raising this and for the update :100:

**Comment by lahinson** [comment]
@michelle-purcell I heard back from the IBM Style Council about plugin/plug-in. The council decided to keep the hyphenated form. They compared it to the term _add-on_, which is still hyphenated. They acknowledged that their answer probably isn't the one we were hoping for. If the CCS style council decides to approve the unhyphenated form, we can  note that as an exception to IBM Style.

**Comment by bergerhoffer** [comment]
Thanks for the update @lahinson!

@michelle-purcell We'll discuss this again at the next SSG meeting (Oct 26) to see if we want to deviate from ISG and go with "plugin" across CCS, or not. Please feel free to attend again if you'd like to be in on the discussion.

**Comment by michelle-purcell** [comment]
Thank you @lahinson and @bergerhoffer for all your efforts with this query and for looking into the option of deviating from ISG. :+1: 

Best regards,
Michelle

**Comment by bergerhoffer** [comment]
I am removing the "IBM input needed" label, since we've received the input :)

**Comment by bergerhoffer** [comment]
@michelle-purcell I have some good news for you :slightly_smiling_face:

We discussed this at today's style guide meeting and decided to move forward with recommending "plugin" without the hyphen in the SSG. Details of the discussion are in today's meeting minutes, but basically folks were good with modernizing and using what upstream communities are using, and don't think losing the hyphen will cause confusion.

Would you be interested in submitting a PR to this repo to add a new entry for "plugin", or would you like an SSG project member to do it?

**Comment by michelle-purcell** [comment]
@bergerhoffer That's fabulous news. Thank you so much to you and the team for taking the time to dive deep into this one.

Absolutely. I would be happy to create a PR for this :+1:

**Comment by michelle-purcell** [comment]
PR #253 submitted for review.

@bergerhoffer - Did the council conclude that we do not use "plug-in" at all? If we do want to permit the hyphenated form, then my PR might need some reworking. Many thanks :-).

**Comment by bergerhoffer** [comment]
@michelle-purcell We didn't talk about that at the meeting, but I replied to this thought in the PR. I think we should do something like noting that it's allowed to be used when you're updating existing content that uses the "plug-in" form, but for new content to use "plugin"

**Comment by michelle-purcell** [comment]
@bergerhoffer +1 to that thought :100:  I updated the PR accordingly to say same.

**Comment by rkratky** [comment]
I'm just reading this, so I'm late to the party, but I'd like to register my disagreement with this approach. Regardless of what I think about the issue at hand, I think it's very confusing to diverge from the IBM Style like this. Realistically, what is the method you'd recommend for keeping track of such differences? How is a docs writer/reviewer expected to know that _some_ guidance from IBM Style does not apply?

**Comment by bergerhoffer** [comment]
Hi @rkratky! The whole point of the supplementary style guide is to build upon the guidance in the IBM style guide (when it's missing guidance for a certain topic we want guidance for) or to document any differences (where we diverge in guidance). 

The SSG itself is how we keep track of the differences. We also keep CCS updated with any new updates to the SSG by emailing regularly, and all updates can be found in the what's new page: https://github.com/redhat-documentation/supplementary-style-guide/blob/main/HISTORY.md

This section of the SSG describes the intent of the SSG and specifies the order of precedence. The SSG should always be checked first before the IBM Style guide: https://redhat-documentation.github.io/supplementary-style-guide/#_how_to_use_this_guide
