### ISSUE TITLE
Consolidating technology preview guidance

### ISSUE THREAD

**Issue by leswilliams44** [redhat-documentation/supplementary-style-guide#216]
Many CCS doc teams use release notes to talk about technology preview content, but there are times when a writer will include technology preview content in the doc to make it clear that the new feature is not supported. Depending on the nature of the changes, there could be several (many?) places that need to call out the technology preview rather than hope the reader has found that release notes notice on their own. We may not know how a user gets to the information (internet search, Customer Portal, searching a specific doc), so we can't assume a single mention in release notes will suffice.

The _Red Hat supplemental style guide_ provides guidance for technology previews, but the content is dispersed across the guide. @naciao did a great job creating technology preview guidelines, so it shouldn't be too hard to rework that content for all of CCS. 

Most of the guidelines in that Source article appear have made it itnto the SSG. The technology preview guidance and disclaimer can be seen cited in the _Specific Documentation Types_ section under Release notes guidelines: https://redhat-documentation.github.io/supplementary-style-guide/#_technology_preview.

https://source.redhat.com/groups/public/ccs/ccs_wiki/template_and_guidelines_for_documenting_technology_preview_features

I am glad to work on this effort, and @ndeevy has graciously offered to help.

**Comment by bergerhoffer** [comment]
If the PR goes through where I add new categories under the style section, I think that we could add a whole new section for this. For example, we will have a whole section for release notes. 

I say that we add a top-level category, where we can add this technology preview section, and we can potentially in the future expand if we want to add more support level information, like Dev preview.

I would have to brainstorm a little harder, but my initial thought is calling the new category something with the word support in it. Maybe even just simply "Support"  would be sufficient.

**Comment by leswilliams44** [comment]
Thanks, @bergerhoffer

**Comment by bergerhoffer** [comment]
@leswilliams44 So I gave this a little more thought. And the only other thing I came up with is that maybe the new "Legal" section I'm proposing in PR #221 could be named "Legal and support" to also house this style entry. Or we could keep them as two separate categories "Legal" and "Support". wdyt?

Or @redhat-documentation/ccs-style-council thoughts?

**Comment by lahinson** [comment]
@bergerhoffer I think I'd keep them as separate sections, but I don't feel too strongly about it.

**Comment by bergerhoffer** [comment]
@leswilliams44 Looks like the consensus is to add a new category file titled "Support" with a subsection for Technology Preview features. I recommend adding this section next to the new "Release notes" category (once my PR is merged - hopefully soon).

**Comment by mjahoda** [comment]
I am adding the guidelines used by the RHEL documentation team [1].

I am also wondering why we use capitalization that is not consistent with other doc types [2]:
- Bug fix
- Known issue
- Deprecated functionality
- but Technology Preview

[1] https://source.redhat.com/groups/public/ccs/rheldocslandingpage/rhel_documentation_master_page_wiki/rhel_release_notes_ccs_guidelines_for_writers#jive_content_id_14_Specific_guidelines_for_each_Doc_Type

[2] https://redhat-documentation.github.io/supplementary-style-guide/#release-notes-doc-texts

**Comment by bergerhoffer** [comment]
This is because (as far as I'm aware) Red Hat's offering of a "Technology Preview" feature is officially capitalized that way. It's not just specific to the release notes doc text.
particular to the 
That is seen everywhere that I'm aware of, both in the snippet we use across docs (https://source.redhat.com/groups/public/ccs/ccs_wiki/template_and_guidelines_for_documenting_technology_preview_features) and the official tech preview support statement (https://access.redhat.com/support/offerings/techpreview/).

We likely should add "Technology Preview" as a glossary item, so that it's clear that it is capitalized this way.

**Comment by bergerhoffer** [comment]
@leswilliams44 Just FYI that TOC reorg PR has been merged, so whenever you (or someone) adds the new "Support" category/file, I'd say that it can go right above the "Release notes" section: https://redhat-documentation.github.io/supplementary-style-guide/#release-notes.

**Comment by leswilliams44** [comment]
Thanks, @bergerhoffer.l I will try to get to it this week.

**Comment by leswilliams44** [comment]
I will also add a glossary entry for the term.
