### ISSUE TITLE
Template for the deprecation notice in the release notes section

### ISSUE THREAD

**Issue by max-cx** [redhat-documentation/supplementary-style-guide#225]
I'm facing an issue with the current wording of the first and second sentences of the template for the deprecation notice in the section about release notes:

![image](https://user-images.githubusercontent.com/78564304/191792647-ebe40540-7125-4b7e-bc91-4b7a77f4975c.png)

Typically, we're writing the release notes in relation to the current release. This means that more often than not, and it's true of our project (Che and Dev Spaces), we provide the deprecation notice in relation to the current release. This means that when the first sentence states that the functionality is deprecated in the current release, that means the functionality is no longer supported in the current release. But if we use the template as it is, the second sentence states completely the opposite.

I understand this is a tricky topic, but at the very least would it be possible to split it into two templates (one for deprecation in the current release and one for deprecation in a future release)? We have a number of authors who use these templates, and we also share these templates with SMEs. Not everyone might notice this contradiction. And not everyone might feel confident to chop up the template. And those who do will have less confidence in using the provided templates.

**Comment by bburt-rh** [comment]
@max-cx If I understand you correctly, for Che and Dev Spaces, when a feature is deprecated in a release, then support for the feature is also simultaneously dropped as of that release. Is this correct?

**Comment by max-cx** [comment]
I see some context here: https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/removed-deprecated-features-platform-updates.

**Comment by max-cx** [comment]
I see some context in https://en.wikipedia.org/wiki/Deprecation.

**Comment by max-cx** [comment]
Let me check with the SME who asked for the latest deprecation notice and ask them what they meant by deprecating that feature and whether they are still offering support and bug fixes for it in the current release, that is the release in which they deprecated the feature.

**Comment by bergerhoffer** [comment]
@max-cx As far as I'm aware, deprecating a feature does not necessarily mean dropping support for it. So the template makes sense to me written as is it - we will still support the existing functionality if you run into issues and fix bugs, but we won't make any enhancements to it.

The actual removal of the feature or removal of support for the feature is when the support would be dropped completely.

**Comment by max-cx** [comment]
@bergerhoffer and @bburt-rh, thank you for your feedback.

Looking at it, I guess I'm contributing to an outlier project with aggressive development, where features get deprecated and removed more often compared to most products. I've reached out to our engineering and support leads to clarify the expectations regarding support, and we (tech writers) can modify the template to account for our specific project context.

Thank you. I'm closing this issue.

**Comment by max-cx** [comment]
@bergerhoffer and @bburt-rh, FYI, just sharing here feedback from the support lead for our product in response to my question:

"

The usual definition [of deprecation]:
- When something is 'deprecated', that means do not use this feature, it is to be deleted at some point in the future.
- So long as the feature is still there (it is only deprecated, not yet removed), it should be allowed fixes for severed bugs/security problems.
- So we should not 'deprecate' unless we intend to delete soon after, because there is the weird state where we patch some problems, but still warn people not to use the feature.
 
"

**Comment by bergerhoffer** [comment]
@max-cx That about matches my expectation, except that users are still technically allowed to keep using the feature when it's deprecated - it's more that they should start trying to move away from it because it will be removed soon.
