### ISSUE TITLE
Suggestions for Commands requiring root privileges

### ISSUE THREAD

**Issue by mjahoda** [redhat-documentation/supplementary-style-guide#235]
https://redhat-documentation.github.io/supplementary-style-guide/#commands-with-root-privileges

> If multiple commands in a procedure require root privileges, add introductory content

Being more specific would be helpful. Do you recommend to include this information as a prerequisite or in the first step?

> The commands in this procedure require root privileges to run. Either run su - to switch

Run scripts, enter or use commands. Not a good role model in a style guide.

**Comment by bergerhoffer** [comment]
I don't have an immediate answer/suggestion to the first item, but for the second, "run" is acceptable to use for commands per the ISG:

![image](https://user-images.githubusercontent.com/7443887/194167692-52907279-3a04-4ace-b1ab-fde0ca237699.png)

But I don't have a strong opinion if others think we should switch it up.

**Comment by mjahoda** [comment]
We used to have the convention I mentioned in the dictionaries among CCS tools.

Just quoting from Emender (https://github.com/emender/documentation-conventions-tests):

blacklistUrl = "[ccs-apps.gsslab.brq.redhat.com/zw/blacklist/text](http://ccs-apps.gsslab.brq.redhat.com/zw/blacklist/text)",

whitelistUrl = "[ccs-apps.gsslab.brq.redhat.com/zw/whitelist/text](http://ccs-apps.gsslab.brq.redhat.com/zw/whitelist/text)",

glossaryUrl = "[ccs-apps.gsslab.brq.redhat.com/zw/glossary/json](http://ccs-apps.gsslab.brq.redhat.com/zw/glossary/json)",

Unfortunately, the tools and the dictionaries are no longer available AFAIK.

Run and issue a command sounds terribly to me, and I would not stick to the IBM Style in this case. It is only slightly better than "execute".

**Comment by jafiala** [comment]
I think we should follow the recommendation "use one term consistently throughout your information." I read this as we should define the common practice and follow it. Enter command is widely used throughout at least RHEL docs (although we do have outliers, hopefully we will be fixing those in the near future through editorial and validation efforts), so I would go ahead and define it in the RH SSG.

**Comment by mjahoda** [comment]
@bburt-rh Well, what about that you in fact are not running commands when you are entering them. After you enter a command, the shell interprets the command, and the shell runs programs and scripts based on the command you entered.

In the first point, I asked for a specific recommendation, not for a strict rule.

**Comment by bburt-rh** [comment]
> In the first point, I asked for a specific recommendation, not for a strict rule.

Fair enough. Why do you think that in this case a specific recommendation is needed rather than a few suggested examples for common use cases? 

> what about that you in fact are not running commands when you are entering them. After you enter a command, the shell interprets the command, and the shell runs programs and scripts based on the command you entered.

Good point. The ISG guidance probably reflects that in everyday usage "run", "type", and "enter" are commonly used as synonyms when talking about user-inserted commands in a CLI even though they literally do not mean the same thing. I think this issue is worth discussing in the next SSG meeting on Oct. 26: https://calendar.google.com/event?action=TEMPLATE&tmeid=N3FqcGVmMXJwc2Vjb2hqbmkwYmNjdHJqYXBfMjAyMjEwMjZUMTIwMDAwWiBiYnVydEByZWRoYXQuY29t

**Comment by mjahoda** [comment]
> a few suggested examples for common use cases

Because I believe that having such a recommendation might result in increased uniformity, which in turn improves scannability.

**Comment by mportman12** [comment]
Style Council meeting outcome: @IngridT1 will reach out to Albert Myles for Support contacts to see if we can glean any info from them. And then we can come back and see how we want to update our guidance.

**Comment by Srivaralakshmi** [comment]
@IngridT1 Any updates/progress on this issue? Please update. Thanks!

**Comment by IngridT1** [comment]
Albert didn't have any good suggestions for this issue. I'm afraid we're still at a stalemate. Maybe we can discuss at the next style meeting?

**Comment by mportman12** [comment]
Discussed at March Style Council meeting. Decided to leave guidance as is and flexible for writer discretion, but determined that some examples may be valuable for readers. @bergerhoffer volunteered to start a PR for this.

**Comment by bredamc** [comment]
@bergerhoffer Ping! Another wee job for you, please and thank you :)

**Comment by bergerhoffer** [comment]
Apologies for the delay. I will try to make some time for this in the next few weeks!

**Comment by bburt-rh** [comment]
@bergerhoffer Were you going to create a PR for this one? If you don't have time, lmk, and I can pick it up.

**Comment by mportman12** [comment]
Considering the delays, @bburt-rh would you be able to take over this issue and create a PR?

**Comment by bburt-rh** [comment]
@mportman12 I can do it. Thanks!

**Comment by bergerhoffer** [comment]
Sorry @bburt-rh and @mportman12 that I never got around to working on this one

**Comment by bburt-rh** [comment]
No worries, @bergerhoffer. I should have a PR out for this one this week.

**Comment by mportman12** [comment]
@bburt-rh Any updates on this?

**Comment by bburt-rh** [comment]
@mportman12 - Will get a PR for this out after OCP 4.14 GA (Oct 31)
