### ISSUE TITLE
Add reciprocal links between the SSG and the stylepedia style guide

### ISSUE THREAD

**Issue by bergerhoffer** [redhat-documentation/supplementary-style-guide#236]
CCS/product docs don't use the style guide at https://stylepedia.net/ (Red Hat Technical Writing Style Guide), but if you came across that page, you wouldn't know that it wasn't for all of Red Hat.

This issue is to add a link in stylepedia style guide linking to the SSG for CCS/product docs, and also to add a link in the SSG linking to the stylepedia style guide for training/exam content.

I am working with @daobrien on the reciprocal wording and will open a PR with the proposed addition shortly.

**Comment by bredamc** [comment]
@bergerhoffer Please add the links (to SSG) within each version of the stylepedia doc (for example, https://stylepedia.net/style/5.1/), and not just on the top-level page (https://stylepedia.net/).

It would be great if the title could be updated too, to indicate the intended audience -- "Red Hat Technical Writing Style Guide -- 
Style Conventions for Writers and Editors" implies that this document is the official style guide for all Red Hat technical writers, which is not the case, and is very confusing for new hires.

**Comment by bburt-rh** [comment]
+1 to the suggestions from @bredamc.  I agree that the current Stylepedia description is confusing, esp. to new members of CCS.

**Comment by bergerhoffer** [comment]
I agree @bburt-rh and @bredamc.  

@daobrien I think we talked about you adding a link to the SSG both on the stylepedia.net landing page and in the actual guide itself, but if not, please consider both locations. Let me know if there's anything we can do to help with your updates.

I've opened PR #251 to add a link to stylepedia from the SSG and it is ready for review!

**Comment by bergerhoffer** [comment]
Our PR to add this has been merged, but I'd like to keep this issue open until the stylepedia.net site and guide have their links to the SSG. @daobrien do you happen to have any ETA for this?

**Comment by daobrien** [comment]
> Our PR to add this has been merged, but I'd like to keep this issue open until the stylepedia.net site and guide have their links to the SSG. @daobrien do you happen to have any ETA for this?

Hi Andrea. All the content is in place and the 6.0 release is going through final QA right now in prep for release in the week of Dec 12.

**Comment by bergerhoffer** [comment]
Excellent, thanks for the update @daobrien!

**Comment by bergerhoffer** [comment]
A link to the SSG has been added to the stylepedia guide here: https://stylepedia.net/style/6.0/#audience

Closing!
