### ISSUE TITLE
Add "sticky" and its derivatives to glossary?

### ISSUE THREAD

**Issue by jseseCCS** [redhat-documentation/supplementary-style-guide#241]
I don't see treatment of "sticky" in either the RHSG or the IBMSG, and it just came up for me today when I was working on a release note (RN). I suggest we add it, whether it's ok to use...the whole gamut. In the context of my RN, "stickiness" = "affinity" according to SME Paul Ferraro. 

Thoughts? Attaching an image of my lil RN for context.
![Screenshot from 2022-10-10 15-03-39](https://user-images.githubusercontent.com/74182792/194935657-e29994dd-b329-49ad-ae06-7855039bba30.png)

**Comment by bergerhoffer** [comment]
IMO session stickiness is a technical concept, so I don't see any reason against using the term. I'd be fine w/ adding the term to the SSG. But would like to hear others' thoughts!

**Comment by sbmetz** [comment]
Adding an entry about general usage sounds good. Also it can help people know whether to use quotes / other special treatment (as in your RN image) or not.

**Comment by roldanbob** [comment]
Although "sticky" and its derivatives might work for English speakers,  I wonder whether the terminology might pose some challenges for translation.  I'd suggest that we'd do better to nudge the guidance toward using some form of "persistence" instead.

**Comment by bergerhoffer** [comment]
I don't claim to be an expert in these terms, but I do believe that these are legitimate technical terms, and not something that people are using "sticky" loosely to describe persistence.

Perhaps it would be better to add the specific terms where "sticky" is okay to use (starting with "sticky session" and "sticky bit"), and not just add "sticky" as a general term alone.

**Comment by mportman12** [comment]
Taking over this one for @jseseCCS

**Comment by mportman12** [comment]
There are 592 search results in documentation for "sticky session" and 490 results for "sticky persistence". Do we want to document both terms as acceptable? Recommend one over the other?
@jseseCCS @bergerhoffer @redhat-documentation/ccs-style-council

**Comment by bredamc** [comment]
I thought "sticky" and "persistent" were synonyms, and that @roldanbob meant that we should use the term "persistent session" (instead of "sticky session"), as opposed to "sticky persistence"? 

If it makes sense to replace the term "sticky" with "persistent", I think we should do so -- but if it doesn't make sense (for example, "sticky bit"), we should retain the term "sticky". Basically, use whichever term would require the least explanation for someone who is not an expert? "persistent" as a general term is more self-explanatory than "sticky"?

**Comment by roldanbob** [comment]
> I thought "sticky" and "persistent" were synonyms, and that @roldanbob meant that we should use the term "persistent session" (instead of "sticky session"), as opposed to "sticky persistence ... Basically, use whichever term would require the least explanation for someone who is not an expert? "persistent" as a general term is more self-explanatory than "sticky"?

Yes, that is my thinking.

**Comment by mportman12** [comment]
@roldanbob @bredamc Got it, I misunderstood. It seems like we don't have a consensus about whether to recommend using "sticky session", "session persistence", or both. I'll add this as a discussion topic for the next Style Council meeting.

**Comment by mportman12** [comment]
Style Council meeting outcome: Document both ‘sticky session’ and ‘session persistence” in the glossary. @mportman12 can take this.
