### ISSUE TITLE
Technology Preview or technology preview?

### ISSUE THREAD

**Issue by jseseCCS** [redhat-documentation/supplementary-style-guide#243]
(Forgive me if this already came up for discussion and I missed it!)

The [IBMSG](https://www.ibm.com/docs/en/ibm-style?topic=word-usage#t) prescribes "technology preview" with initial lowercase letters. The [RHSG](https://redhat-documentation.github.io/supplementary-style-guide/#_t) calls for initial caps. I want to make sure we choose one spelling and stick with it since that's part and parcel of uniting the two SGs. 

Which do we want? My vote is for initial lowercase letters since it's not a proper noun. Others?

**Comment by bergerhoffer** [comment]
@jseseCCS We actually just added the "Technology Preview" entry [1] within the last week or so (along with other TP guidance, including a template [2]).

It has been pretty consistent within CCS that Red Hat uses "Technology Preview" capitalized (including in the official support scope statement [3]). And also with the template we've been using within CCS for a few years (on the source [4]).

So I'd safely say that this one is pretty set as is, capitalized.

[1] https://redhat-documentation.github.io/supplementary-style-guide/#technology-preview
[2] https://redhat-documentation.github.io/supplementary-style-guide/#technology-preview-guidance
[3] https://access.redhat.com/support/offerings/techpreview/
[4] https://source.redhat.com/groups/public/ccs/ccs_wiki/template_and_guidelines_for_documenting_technology_preview_features

**Comment by jseseCCS** [comment]
apologies, @bergerhoffer! i thought we were working on merging the two style guides, meaning that, anywhere there's conflicting info, we choose one of the two opposing methods and then follow it. if we choose the IBM way, we make no SG changes (after guides merged). if we choose the RH way, we merge guides, but have a note in the term definition that says something like, "Red Hat writers should use 'Technology Preview'." i'm wrong, huh?

**Comment by bergerhoffer** [comment]
@jseseCCS Nope, we're not merging the two style guides. If both the SSG and the ISG have guidance about the same issue, the SSG takes precedence.

Take a look at this section, which explains it: https://redhat-documentation.github.io/supplementary-style-guide/#_how_to_use_this_guide

We don't duplicate guidance that is in the ISG that we agree with. But we do sometimes override guidance in the ISG if we do something differently at Red Hat, which we do in this case with Technology Preview.

**Comment by jseseCCS** [comment]
ah ha. that makes sense. i'll take a look, and thanks, as always, @bergerhoffer!

**Comment by bergerhoffer** [comment]
No problem! I'm closing this issue, but feel free to reopen if you think there is more to discuss. Thanks!

**Comment by jseseCCS** [comment]
sounds good. thank you!
