### ISSUE TITLE
Add "Solution" to glossary?

### ISSUE THREAD

**Issue by jknilans** [redhat-documentation/supplementary-style-guide#245]
I noticed that there are many instances of the term "Solution" used in the style guide, and we use it for top-level navigation on the main Red Hat website as well, but I don't see a definition for what exactly we mean when we use the term in the glossary.

It would be great to understand how we use the term "Solution" and what we define as a solution. E.g. is a solution basically a [Red Hat or partner product](https://www.redhat.com/en/solutions/it-automation) used in a specific context like in this example for Ansible automation? Is it a combination of [Red Hat product + partner product](https://www.redhat.com/en/partners/isv) used in this example where we talk about ISV products that run on Red Hat platforms? Is it something else?

**Comment by bergerhoffer** [comment]
I don't have a good answer here, and we'll likely need to ask outside of CCS to find a real definition, if there is one. My guess is that it is a general term that could cover a lot of situations. Could be a single product, could be a combo of products or technologies or partner products to solve a particular situation. I'm not positive if there will be a true definition for what we mean by "solution" at Red Hat, but we can definitely investigate. 

Anyone have any thoughts on this, or thoughts on who we can check with? My first thought is the folks who maintain the official RH product and solutions name spreadsheet.

**Comment by bergerhoffer** [comment]
Discussed at the 30 November SSG meeting.

@jknilans Can you tell us a little more about your case for needing to know this definition? Our SSG is really only aimed at product documentation, and this seems like it might be more of a marketing or other communications question. There is a corporate style guide, (though I don't see this listed), and this might be more of a question for the naming team. Let us know if this really is for product docs, or if you need help with contacting the naming team. Thanks!

**Comment by jknilans** [comment]
Hi @bergerhoffer, I didn't realize this was only for product docs. I work on the Ecosystem Catalog, which provides customers with a view of both Red Hat software products and certified hardware, software, and cloud partner products. 

We were looking to include solutions, but we weren't sure if there was a specific way that Red Hat uses the term or not, since it seems like it's currently used in different ways. 

I talked with the team responsible for partner solutions, and we have a definition that we'll use going forward so I think we're okay to close out this issue.

Thanks!

**Comment by bergerhoffer** [comment]
Okay great thanks @jknilans!
