### ISSUE TITLE
SSG guidance on the term BIOS should be updated

### ISSUE THREAD

**Issue by aireilly** [redhat-documentation/supplementary-style-guide#249]
While not technically inaccurate, the section on [BIOS](https://redhat-documentation.github.io/supplementary-style-guide/#bios) could do with a refresh. BIOS is the specific name for the motherboard firmware in older PCs. Modern computers have a different kind of firmware which is called either EFI or [UEFI](https://en.wikipedia.org/wiki/UEFI).

We often use the term BIOS to refer to computer firmware in Red Hat docs. This is technically inaccurate, "firmware" is a more accurate term. Some StackExchange background: https://superuser.com/questions/879908/what-is-the-difference-between-bios-and-firmware 

Suggestion: Update the guidance on BIOS to "Use with caution", and where the writer needs to refer to computer firmware, instead of using BIOS as a general term, use a more specific phrase like like "firmware" or "UEFI firmware or legacy BIOS" instead.

**Comment by bburt-rh** [comment]
@aireilly I think this is a great suggestion and am in favor of making this update. (I can't remember the last time I had a computer that used BIOS!)

**Comment by sbmetz** [comment]
@bburt-rh and @aireilly -- want to take a look at my proposed changes in the linked PR?

**Comment by bburt-rh** [comment]
@sbmetz - I put in some review comments. PTAL when you get a chance

**Comment by aireilly** [comment]
FYI - the "use with caution" image was not added to the BIOS title

**Comment by bergerhoffer** [comment]
Good catch @aireilly, thanks! I'll submit a PR for it, since I noticed one other minor nit.
