### ISSUE TITLE
Add the Vale linter style validation check to the CCS-SSG github PR workflow

### ISSUE THREAD

**Issue by michelle-purcell** [redhat-documentation/supplementary-style-guide#260]
Integrating the Vale linter tool on style guide PRs not only helps us to ensure that the style guideline content _actually_ follows the SSG guidelines but also will help to enhance the quality of the Red Hat vale rules developed in the [vale-at-red-hat ](https://github.com/redhat-documentation/vale-at-red-hat/)community project.

Sometimes when we are adding new guidelines, we forget to apply some of the great advice that we define. I know I am guilty of this for sure :blush:

The  phrases “_eating your own dog food_" and "_fish-fooding_" jump to mind here!

**Comment by aireilly** [comment]
One thought that occurs to me - how would you error words that appear in the body of the SSG? Perhaps a custom vale.ini to ignore the glossary files.

**Comment by bergerhoffer** [comment]
@aireilly wouldn't the point of the Vale checks be to check the glossary files too?

I don't personally have any experience with setting up Vale in a CI, but if anyone in the project is interested in tackling this, please speak up! CC @redhat-documentation/ccs-style-council

**Comment by aireilly** [comment]
@bergerhoffer It would, but since most error terms are listed in the glossary, it would throw errors for those instances. Not ideal, but maybe not a big problem. Ideally, I think you would want to not flag instances of the error in the body of a glossary entry for that error - if that makes sense...

**Comment by bergerhoffer** [comment]
Yeah I guess I don't know how you'd solve that, other than people just looking case by case to ignore. It seems that with vale output, there are a lot of hits that you have to ignore anyways, so I wouldn't think it should be too big of a deal.

**Comment by mportman12** [comment]
Style Council meeting outcome: @bburt-rh volunteered to work with Aidan on this.

**Comment by aireilly** [comment]
BTW, once [this PR](https://github.com/redhat-documentation/vale-at-red-hat/pull/410) is merged, we'll have pretty much full SSG coverage for "do not use" terms in Vale.

**Comment by Srivaralakshmi** [comment]
@bburt-rh and @aireilly: Thanks for volunteering to work on this issue. I see that [the PR](https://github.com/redhat-documentation/vale-at-red-hat/pull/410) is merged. 

- What is the next step?
- Is there pending work to be done as part of this issue? Or can we close this issue now?

Please clarify and confirm. Thanks again!

**Comment by bergerhoffer** [comment]
@Amrita42 We've removed you from the ccs-style-council group, but we can't stop you from receiving notifications for open issues/PRs that you've already been receiving notifications from. You can try using the "Unsubscribe" button on individual issues/PRs though if you'd like.

**Comment by aireilly** [comment]
@bburt-rh was working on this. Not sure how much progress he has made.

**Comment by Srivaralakshmi** [comment]
Thanks for the update @aireilly.

@bburt-rh Any update on the progress you have made so far on this one?

**Comment by bburt-rh** [comment]
@Srivaralakshmi @aireilly Thanks. Haven't had time to start on this, as I've been unavailable for most of March. The earliest I'll be able to start in on this will be mid-April.

**Comment by mportman12** [comment]
@bburt-rh any updates on this?

**Comment by aireilly** [comment]
@bburt-rh this should be pretty straightforward to set up. I can jump on a call to assist. Hit me up on slack.

**Comment by bburt-rh** [comment]
Thanks @aireilly - let's try to tackle this one next week! I'll ping you in Slack.

**Comment by bergerhoffer** [comment]
Closing because #402 was merged to add vale checks to the SSG.
