### ISSUE TITLE
Add "devfile" to RH SSG?

### ISSUE THREAD

**Issue by jseseCCS** [redhat-documentation/supplementary-style-guide#281]
hi, y'all!

yesterday i had the occasion, for the first time in a long time, to deal with the word "devfile." i didn't realize that it's always written like that: one word, lc d when not the first word in a sent. when i looked to check it, i couldn't find it in the IBM SG or in ours. should we add it? entry would read something like this, i imagine:

devfile (noun)
**Description**: A file that describes and define a development environment. (<-- got that [here](https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.11/html/end-user_guide/authoring-devfiles_crw).)
**Use it**: yes
**Incorrect forms**: dev file, .dev file, dev-file
**See also:** ?

thoughts?

**Comment by bergerhoffer** [comment]
@jseseCCS Is this term of "devfile" specific to CodeReady Workspaces (and the glossary entry would specify this)? Or is this a term that is supposed to be more widely used for any file that describes a development environment?

If it's not just limited to CodeReady Workspaces, then the description seems a little broad.

**Comment by dfitzmau** [comment]
Should the SSG only cover terms that would make it into our customer docs? I feel "devfile" might reside outside our docs and be a term relevant to the development stage of a product.

**Comment by Srivaralakshmi** [comment]
+1 to @dfitzmau. @redhat-documentation/ccs-style-council Any thoughts/opinion on this? Welcome your perspective and input.

@jseseCCS Can you please respond to the question from @bergerhoffer? Thanks!

**Comment by jseseCCS** [comment]
@bergerhoffer sorry for the delay! 

Devfile is not only for CodeReady Workspaces. Developers can use it for any build environment. (Devfile doc is [here](https://devfile.io/docs/2.2.0/what-is-a-devfile).) if we do include this, I can certainly get a better descr from the Devfile.io doc site. i'd suggest something like this:

A devfile is a yaml file that you can include in your local development environment to automate various build processes and apply environment guidelines. Specifically, devfiles can provide guidance for runtime images, example code, build and CI commands, and deployment options like workspace servers and containerization.

wdyt?

thanks for the nudge, @Srivaralakshmi!

**Comment by jseseCCS** [comment]
@bergerhoffer thank you! i can do it. is tomorrow ok?

**Comment by jseseCCS** [comment]
created a PR to add this to the glossary. i'll get a SME review first from either someone @inoxx03 suggests or one of my teammates, and then I'll need peer reviews. FYI and thanks!

[PR 304](https://github.com/redhat-documentation/supplementary-style-guide/pull/304)

**Comment by dfitzmau** [comment]
> @bergerhoffer _Devfile_ is a term recognized outside outside the context of the Red Hat product portfolio. @jseseCCS provides an excellent description for it.
> 
> @dfitzmau To your point about doc relevance of the term _Devfile_: It is a structured templates that contains reproducible build environment configuration data and can be consumed by some of our DevTools products (HACBS was one such product, RHTAP is, AFAIK, another) It is not on the same level as, say, the product UI in terms of how exposed it is to customers, but if the product being documented is intended to be used to create reproducible build environment setups for development, then the customer using the product will inevitable touch Devfiles at some point, too (in the same way container app developers and DevOps need to create and edit Dockerfiles when they develop and deploy). Because of this, you will most likely end up mentioning Devfiles in customer facing documentation, and so, it makes sense for this term to be covered in the SSG.
> 
> Disclaimer: I could be wrong, tho...

AH, @inoxx03 , that is you. Your username and picture were originally clouded in mystery :) . Thanks for the explanation. I just wanted to check in case we were adding extremely rare terminology to the SSG. I was looking at the housecleaning aspect of maintaining a term list.

**Comment by mportman12** [comment]
Closing issue because PR has been merged.
