### ISSUE TITLE
Add "Dockerfile" to RH SSG?

### ISSUE THREAD

**Issue by jseseCCS** [redhat-documentation/supplementary-style-guide#282]
hi, y'all!

yesterday i had the occasion to deal with the word "Dockerfile." when i looked to check it, i couldn't find it in the IBM SG or in ours. should we add it? entry would read something like this, i imagine:

Dockerfile (noun)
**Description**: A text document that contains all the commands a user could call on the command line to assemble an image. (<-- got that [here](https://docs.docker.com/engine/reference/builder/). needs tweaking.)
**Use it**: yes
**Incorrect forms**: dockerfile, docker file, Docker file, 
**See also:** ?

thoughts?

**Comment by bergerhoffer** [comment]
Hey @jseseCCS! I just checked and we do actually have Dockerfile already defined in the SSG: https://redhat-documentation.github.io/supplementary-style-guide/#dockerfile

Let me know if that entry looks good, or if you have anything you think we need to add for it. Thanks!

**Comment by jseseCCS** [comment]
not sure how i missed it, @bergerhoffer. thank you!! closing!
