### ISSUE TITLE
Accessing contributors committed changes from a local system 

### ISSUE THREAD

**Issue by dfitzmau** [redhat-documentation/supplementary-style-guide#285]
I'm not sure how useful reviewers would find some commands that could provide them a way to access proposed changes in a PR from their local system. 

Maybe a reviewer has a sketchy internet connection and might want to perform a review offline, or a reviewer might want to perform a distraction-free review because the PR on the GitHub web UI is receiving a lot of discussion activity.

I have some commands that can provide a reviewer with this capability. Please let me know your thoughts and where these commands go be placed in the repo.

**Comment by bergerhoffer** [comment]
I don't have any issues with doing the review through the UI (I also always check out locally to do a build if the person doesn't provide a preview). But if anyone else thinks that this would be valuable to add instructions for somewhere, then definitely could add them to our internal resources. @redhat-documentation/ccs-style-council would anyone benefit from this?

**Comment by bburt-rh** [comment]
I usually do the review through the web UI as well, so I'm not one who would benefit. 

@dfitzmau What exactly are the commands you had in mind? Are these bash scripts?

**Comment by bburt-rh** [comment]
Just as a point of information, I've found the most straightforward way to check out other people's PRs to read on my local machine is to use the `gh` CLI utility: https://github.com/cli/cli
