### ISSUE TITLE
Glossary entry "we suggest (verb)" suggests to use "recommend"

### ISSUE THREAD

**Issue by mmuehlfeldRH** [redhat-documentation/supplementary-style-guide#290]
https://redhat-documentation.github.io/supplementary-style-guide/#we-suggest

According to the glossary entry "we suggest (verb)", writers should use "recommend". However, the IBM Style Guide warns that recommendations can cause legal problems.

"See also" of this entry refers to the "recommended" glossary entry - which is flagged as "use it: no".

**Comment by dfitzmau** [comment]
Thanks, @mmuehlfeldRH , for raising this issue. Yeah, the word "recommend" when coupled with "Red Hat" can potentially open legal issues for sensitive scenarios, such as fiddling with security settings and so on. I usually put the onus on the user by asking them to consider the consequences and how Red Hat does not take responsibility for x and y. Of course, approvals from various SMEs on such clauses is essential. 

I'm curious to know what others think.

**Comment by bergerhoffer** [comment]
+1 for removing "recommend" as an acceptable alternative for "we suggest". I can submit a PR to adjust the entry.

**Comment by bergerhoffer** [comment]
Opened #294 to address this
