### ISSUE TITLE
The "external links" section doesn't define what "external sites" means

### ISSUE THREAD

**Issue by mmuehlfeldRH** [redhat-documentation/supplementary-style-guide#291]
https://redhat-documentation.github.io/supplementary-style-guide/#external-links:

> Avoid links to external sites when possible. External links can change or be unreliable.

"external sites" is vague. Can we enhance this entry and be a more specific?

Does it mean only links under redhat.com? What about other domains under our control like docs.openshift.com? Can we link docs from IBM?

**Comment by mportman12** [comment]
Good question. I would assume this would apply to non-Red Hat affiliated sites, like Microsoft and AWS.

**Comment by bergerhoffer** [comment]
Honestly, even links under redhat.com can break. I think the last time I looked at the broken link report for OCP, the majority if not all of the broken links were to access.redhat.com docs. (Though that could be because that is the majority of what we link to). 

This guidance is probably purposefully vague as a general warning that any link that is not being tested as part of your doc set can break, and to try to reduce them. We don't say to never do it, moreso just to do it with care. Let us know if you think this is sufficient, or if we need to work on the wording more.

**Comment by mmuehlfeldRH** [comment]
I would prefer some guidance in the SSG what is considered as external. Perhaps even with a list of domains we can link.

> Does it mean only links under redhat.com? What about other domains under our control like docs.openshift.com? Can we link docs from IBM?

**Comment by dfitzmau** [comment]
Good point, @mmuehlfeldRH .

Would external be anything outside the Red Hat private network? A good definition would help for sure with settling what truly is "external".

**Comment by dfitzmau** [comment]
Anyone know of the best starting points for this issue? Internal DPMs and CSs? Projects can be so varied, so defining a one-stop rule might be difficult. Third-party software projects might need to use external links to credit the owner of the software.

**Comment by bburt-rh** [comment]
I that that it'd be beneficial to have a more specific definition of what we consider to be "external" links. I've always assumed it meant "any site outside of the specific site containing the documentation for the product you're documenting". So to me that would mean any URLs outside of the Customer Portal (access.redhat.com) or specific product sites (e.g. docs.openshift.com). But implied definitions are not as good as explicit ones, imo, so I'd argue that creating an explicit definition would be a good thing.

I agree with @bergerhoffer that the overall guidance is perhaps left purposely vague to allow for flexibility. However, I also think that having guidance for specific situations might be helpful (e.g. external links to GitHub content). 

So, maybe we should consider doing two things:

- Define more explicitly what we mean by "external" sites.
- Gather a list of sites/links that might require special handling, such as GitHub links.

What would other people think of this approach? 

I suggest that we add this to the agenda for our next meeting. I'd be willing to take on the issue if we decide that a change is desirable.

**Comment by Srivaralakshmi** [comment]
+1 to @bburt-rh and @bergerhoffer.

**Comment by mportman12** [comment]
Discussed at March Style Council meeting. Determined that GitHub link requirements may be OpenShift specific and we want to limit product-specific style guidance outside of the glossary. @bburt-rh to update the external link guidance to clarify what we mean by "external" (non-Red Hat and non-IBM) and to add link to the [Publication of other organizations or individuals](https://www.ibm.com/docs/en/ibm-style?topic=references-citations#publications-of-other-organizations-or-individuals) section in the ISG.

**Comment by mportman12** [comment]
@bburt-rh any updates on this?

**Comment by bburt-rh** [comment]
@mportman12 I plan to have a PR for this out for review by next Thursday at the latest. Thanks for the reminder!
