### ISSUE TITLE
Add a glossary entry for "replatforming"--when to use it and how it is different from other similar terms

### ISSUE THREAD

**Issue by IngridT1** [redhat-documentation/supplementary-style-guide#296]
In Word Nerds Lauren Pritchett from opensource.com brought up the terminology "replatforming", because she was editing an article with this term. 

The term is new and similar to "lift and shift", but seems to be becoming widely used in marketing to describe moving to OpenShift. We need to do some research and add the term to the Red Hat Supplementary Style Guide glossary, so that people are using it correctly, when (if?) it is appropriate. 

@inoxx03 (with help from @mportman12) is going to work on this entry.

**Comment by Srivaralakshmi** [comment]
This has the potential for a PR. As the issue creator, would you like to create the PR, or would you prefer someone from the @redhat-documentation/ccs-style-council to do it for you?

**Comment by Srivaralakshmi** [comment]
> This has the potential for a PR. @IngridT1 As the issue creator, would you like to create the PR, or would you prefer someone from the @redhat-documentation/ccs-style-council to do it for you?

@IngridT1 Please respond.

**Comment by mportman12** [comment]
@IngridT1 any updates on this?

**Comment by bredamc** [comment]
@inoxx03 If you can provide the text for the new glossary entry "replatforming", we can arrange for a member of the style council to create the PR?

**Comment by mportman12** [comment]
@inoxx03 Do you have an update on this?

**Comment by IngridT1** [comment]
@mportman12 I think I'm ultimately responsible for this PR. Apologies. Let me write something and see what I can do with my rusty Git skills.

**Comment by IngridT1** [comment]
I'm looking up definitions for replatforming, and I'm beginning to think that this is not a term that we'll see in our content. Maybe it's more marketing-focused? 

Sample definition:

> Replatforming is a cloud migration strategy that involves modifying a legacy system to work optimally in the cloud without rewriting its core architecture.

From: https://www.cloudzero.com/blog/replatforming

I just did a search for the term on access.redhat.com and nothing came up. Thoughts?

**Comment by mportman12** [comment]
@IngridT1 If the term has never been used in product docs (or KB articles and solutions), then I agree we don't need to add it to the glossary at this time.

**Comment by IngridT1** [comment]
Is it okay to close the issue?

**Comment by mportman12** [comment]
I'll close it.
