### ISSUE TITLE
Add "image builder" as a glossary entry

### ISSUE THREAD

**Issue by elianerpereira** [redhat-documentation/supplementary-style-guide#309]
Hello everyone, 
I would like to ask to add "image builder" as a glossary entry, please.
The Marketing team informed that all mentions "Image Builder" should be made in lowercase "image builder"
The reason is that, according to Marketing team, is:
"> We do not capitalize operators, components, features, etc. Our naming standards dictate that we reserve capitalization for product names (that are sku'd) in order to help further distinguish products from other offerings."
Please, it is possible to add this entry? 

Thank you so much.

**Comment by bergerhoffer** [comment]
@elianerpereira The guidance to lowercase might be correct in this case, but I do want to point out that marketing content has different rules and requirements than we do in product documentation. 

Some things that cannot be capitalized in marketing content might be correct to capitalize in product documentation. One example of this is operators - in product docs we do capitalize operators, and the brand team acknowledges this. (I can share the slides where they acknowledge this through another channel, it's not a public slide deck). 

Again, your instance here might still be correct to lowercase, I just wanted to state that there are cases where we can differ.

**Comment by bredamc** [comment]
@elianerpereira Can you please provide an update about the "Image Builder" term? Do we still need a glossary entry? The term is currently used in the _commit_ glossary entry:
https://redhat-documentation.github.io/supplementary-style-guide/#commit

**Comment by elianerpereira** [comment]
Thank you so much for all the inputs. @bredamc this is why we (image builder team and docs for image builder) decided to adopt "image builder":

"Marketing changed all mentions of "Image Builder" to "image builder"
in Ondřej's (fantastic) blog post [1]. We wondered why, because we
have always capitalized it, including in RHEL documentation.

Alas, it turns out that lower-case is correct. Kristin from marketing
told me that

> We do not capitalize operators, components, features, etc. Our naming standards dictate that we reserve capitalization for product names (that are sku'd) in order to help further distinguish products from other offerings.

I have always thought of image builder as a product! I'll open a
discussion with the BU to see what they think. Just wanted to let you
know in case you're wondering. Let's go with the official (lower-case)
spelling for now.

Lars"
This is also in the Official rd Hat product name list: https://docs.google.com/spreadsheets/d/1DLS_lS3VKidgZIvcLmLp9BoiqptkvqHWfe1D5FD2kfk/edit#gid=1375785039

Thank you!

**Comment by bredamc** [comment]
@elianerpereira It seems that we need to either update "Image Builder" to "image builder" in the _commit_ entry in the glossary, or remove that sentence? If we update it, we should probably do so in tandem with similar updates in the _image builder_ documentation? 

Is there a noun that we could use, to avoid starting the sentence with a lowercase letter? In the following example rewrite, I used the word "component" -- is that term accurate?
"The image builder component generates an OSTree commit for RHEL for Edge images. "

**Comment by bredamc** [comment]
@bergerhoffer @mportman12 FYI -- what do you think?

**Comment by mportman12** [comment]
@bredamc @elianerpereira Or, if "image builder" is at the beginning of a sentence, would the "I" be capitalized?
e.g. "Image builder generates an OSTree commit."

**Comment by bredamc** [comment]
I think that, given that the advice is to use lowercase letters for the name, we should rewrite to avoid starting a sentence with that name, so that we don't have to use the capital _I_.

**Comment by elianerpereira** [comment]
That sounds good to me, @bredamc 
I will rewrite the sentences to void starting a sentence with that name, so that we don't have to use the capital I.
Thank you!

**Comment by bredamc** [comment]
@elianerpereira The only reference in the SSG uses the same capitalisation as the (not yet updated) docs. Do you want to put this issue on hold until the docs have been updated (and then update the reference in the SSG), or remove that sentence from the SSG?

**Comment by elianerpereira** [comment]
@bredamc please, if possible, I would like to put it on hold till all the content is updated. Thank you!

**Comment by elianerpereira** [comment]
You can close this in the meanwhile, and I can open a new issue in the future. Thank you.

**Comment by mjahoda** [comment]
Hi, I'm sorry for posting to a closed thread, but after re-reading the discussion + some real-life experience, I believe we should do almost the opposite. I'd add "Image Builder" to the glossary, because the goals of product (tech) and marketing docs differ. In the second comment, @bergerhoffer pointed out we don't follow the marketing guidelines also in other cases (OpenShift operators). And when I read sentences using the lowercased name, for example:
- "By default, image builder specifies `rhel/{ProductNumber}/$ARCH/edge`..."
- "...build a new commit with image builder."
I do believe that the majority of readers would be less distracted if we unify on the capitalized version. We also do not use (c) or TM in product docs, and we should prioritize clarity.

**Comment by jafiala** [comment]
I agree with mjahoda here (and I know we had discussed this in the mtg and even earlier internally with Eli). Using "image builder" reads just like a generic type of utility, similar to how we use "package manager" or "text editor", which is misleading. [Image Builder is the name of a specific tool](https://developers.redhat.com/blog/2019/05/08/red-hat-enterprise-linux-8-image-builder-building-custom-system-images), and we should write it as such, even though it is not a product.

**Comment by bergerhoffer** [comment]
Reopening this issue based on the latest comments.

**Comment by elianerpereira** [comment]
Thank you for the inputs!
I am talking to PM, Marketing, and Branding team, and have been working to transition away from capitalizing "image builder" references. They decided to standardize on the following naming: RHEL image builder

**Comment by bergerhoffer** [comment]
@mjahoda @jafiala @elianerpereira Are you interested in joining next week's SSG meeting (8 AM ET) to discuss this?

I don't know if any other SSG project members have background with this term, so I don't want us to make a decision on something that we don't have experience with.

I'm not sure whether "image builder" lowercase is correct, or if this is one of those exceptions where we deviate from marketing with capitalization. 

Not sure if there are other writers out there that also work with this term that could also weigh in?

**Comment by mportman12** [comment]
Discussed at the September Style Council meeting: The PM, Terry Bowling, is really sure and pushing for RHEL image builder in the docs. So @elianerpereira will send an email to all image builder stakeholders to understand their reason behind the name and share the information with us.

**Comment by bergerhoffer** [comment]
@elianerpereira Let us know if this is still an issue that needs to be investigated, or if we should close this. (It can always be brought up again at a later time, if needed). Thanks!

**Comment by elianerpereira** [comment]
Hello, sorry for the delay. This can be closed. The team decided to use image builder all lower case. Thank you.
