### ISSUE TITLE
Add "Pod" to glossary

### ISSUE THREAD

**Issue by abigaeljamie** [redhat-documentation/supplementary-style-guide#31]
Can we please add "Pod" in the "[General conventions](https://redhat-documentation.github.io/supplementary-style-guide/#_p)" section? I see it written as "Pod" (not "pod") in other areas of the guide, but it would be great to have it documented so that folks can quickly find it and see its capitalization.

**Comment by bergerhoffer** [comment]
Hi @abigaeljamie, we're actually in the process of updating our terminology style guidance on OpenShift, and this guidance will become "pod" lowercase. See https://github.com/openshift/openshift-docs/pull/26111 for details.

This should be getting merged in and applied in the next week or two, and I have it on my list to come through and update OpenShift's glossary items here afterward. 

We do have an entry for "Pod" in the OpenShift section, if you look under product-specific conventions. Do you see a case for adding it to the general conventions area too?

**Comment by abigaeljamie** [comment]
Thank you, @bergerhoffer ! I didn't initially see "pod" listed in the OpenShift section. So since it's already documented, then no I don't see a case for adding it to the general conventions area. 

And good to know about "Pod" changing to "pod" 👍 I'll keep that in mind! 

Thank you for your help!
