### ISSUE TITLE
Accessibility guide tracker

### ISSUE THREAD

**Issue by bergerhoffer** [redhat-documentation/supplementary-style-guide#316]
A Red Hat accessibility guide is in progress by @dcdacosta. Once that is available, we should update the SSG to link to it.

Possible updates:

1. Add the accessibility guide to the list of [Related Red Hat guides](https://redhat-documentation.github.io/supplementary-style-guide/#_related_red_hat_guides)
2. Add a top-level "Accessibility section"
   - This section could either be just a link to the accessibility guide, or it could have some basic/most important accessibility highlights and tips here (like what is in the cloud services accessibility section)
3. Remove the "Accessibility" section that is under "Cloud services guidelines" (or incorporate the guidelines to the new top-level "Accessibility" section)
    - This is because these are general accessibility guidelines that apply to all docs, not just managed services.

**Comment by bergerhoffer** [comment]
Marking this "on hold" until the accessibility guide is available.

**Comment by mportman12** [comment]
@bergerhoffer Accessibility guide has been published:
https://redhat-documentation.github.io/accessibility-guide/
Can you create a PR for this?

**Comment by bergerhoffer** [comment]
@mportman12 We could definitely easily just add a link to the new guide, but I think it's worth investigating the options I proposed in the description above. I have it as a discussion topic at the next SSG meeting. So holding off on any PRs until then.

**Comment by mportman12** [comment]
@bergerhoffer We got several pieces of feedback in the SSG survey asking for an expanded accessibility section. I agree that it's oddly located under Cloud services, and we should look into moving it or creating a non-product specific accessibility section. We should avoid duplicating information that's in the accessibility guide, though.

**Comment by bergerhoffer** [comment]
Opened #329 to add the new guide link and make a few other restructuring moves based on the fact that the guidelines in the cloud services section really apply to all docs, not just cloud servicfes
