### ISSUE TITLE
Does CCS deliver books?

### ISSUE THREAD

**Issue by gregraka** [redhat-documentation/supplementary-style-guide#317]
We're doing a reboot on our RHOSP titles. The ISG says that "books" should use headline capitalization. However, RHEL doesn't, and lot of product doc sets are inconsistent. Are our "deliverables" considered "books?" Regardless of the terminology, should our "deliverable" titles use sentence-style or headline-style capitalization? Thanks for helping us to figure this out!

**Comment by mportman12** [comment]
On RHEL, we only capitalize the first word in a title or heading. I can't find any official guidance in the SSG or Mod Docs guide. IIRC, this is because some products use title case. @bergerhoffer Do you know any more about the capitalization inconsistency?

**Comment by bergerhoffer** [comment]
This is a great question - and one that I think @bburt-rh and I discussed a few months ago and realized needed some clarification.

I'm used to using sentence case for all headings, titles, anything of the sort - including a guide's title. It could have just been my misunderstanding, but I had thought when we changed away from title case to sentence case a few years ago, that that meant we did it across the board. @IngridT1 might have more history on this or an answer here.

But IMO it seems confusing to have title case some places and sentence case elsewhere. Seems easier and more consistent to just use sentence case across the board. But that's just my 2 cents and guidance to back it up.

**Comment by gregraka** [comment]
LOL. I asked @IngridT1 and she suggested that I enter a supplementary SG issue.  :^)

What we need is an unambiguous statement. Perhaps something like?

````
Titles that appear under Product Documentation on the Red Hat Customer Portal should use **sentence-style** capitalization.
````

WDYT?

**Comment by IngridT1** [comment]
That was an interesting journey through our docs. I'd say that about 50% or our titles use title case and about 50% use sentence case for guide titles. 

It looks like OpenShift and RHEL, our biggest offerings, have _pretty much_ settled on sentence case, so that seems like the best path forward. 

I'd recommend standardizing on sentence case. 

Do you want to do a survey or send out an email and ask the question: Does your team use sentence case or title case when titling guides? Or do you just want to discuss it in a team meeting?

**Comment by mportman12** [comment]
June SSG meeting outcome: @mportman12 to create PR to add entry to recommend sentence case for all titles. Will also contact about updating their guidance to include modern online product docs (and maybe clarify if the “book titles” mean traditional print books?).

**Comment by mportman12** [comment]
Created [PR](https://github.com/redhat-documentation/supplementary-style-guide/pull/354).

**Comment by bergerhoffer** [comment]
PR has been merged, closing this issue.

Thanks @gregraka for raising this!

**Comment by gregraka** [comment]
Thanks, @bergerhoffer, @mportman12, and everyone who worked on this PR. This is a big help!

**Comment by mportman12** [comment]
@bergerhoffer @gregraka I reread the [ISG chapter](https://www.ibm.com/docs/en/ibm-style?topic=grammar-capitalization#headings-titles-and-banners) on capitalization of headings, titles, and banners. Under Headline-style capitalization, they list `Titles of stand-alone information units, such as quick start guides or discrete sets of product
documentation`. 
One of my to do items for this ticket was to ask ISG to add product documentation to their list of capitalization guidelines (for either sentence- or headline-style capitalization), but upon review, it seems like online product docs are already there. As such, I don't think there's any need to contact the ISG about this.

**Comment by gregraka** [comment]
Hi, @mportman12. Yes, I agree. It looks like the ISG is saying that IBM product documentation uses headline-style capitalization. Thanks for investigating this!

**Comment by IngridT1** [comment]
@bergerhoffer @mportman12 @gregraka Does this change anything about our recommendations? It sounds like we've decided to recommend sentence case for guide titles, and we have added that guidance to the SSG. Is there more?

**Comment by bergerhoffer** [comment]
I don't think so. I think we're good.
