### ISSUE TITLE
Add "codebase" (or "code base"?) glossary entry?

### ISSUE THREAD

**Issue by jseseCCS** [redhat-documentation/supplementary-style-guide#319]
Hi, teammates!

As one does, I had to deal with the word(s?) "code base" today, and not for the first time, I wondered, "Is that one word or two?" Turns out, neither the IBM SG nor our own SSG addresses that term. Long-ish Slack chat with @bergerhoffer @dfitzmau and @sbmetz later and here we are.

1. Do we like "code base" or "codebase"?
2. Do we agree that we should add it to our SSG gloss?

Here's the sentence I saw it in today, for context: "App Studio serves as both the upstream code base for documentation and as a community for learning, help, and knowledge sharing."

Thanks for your thoughts!

**Comment by mportman12** [comment]
We have a relatively similar number of uses for both spellings in documentation. While Googling the terms, most of the documentation on the internet referred to this as "codebase, sometimes written as code base". This has me leaning towards codebase, one word.

**Comment by jseseCCS** [comment]
thanks for your input, everyone! what's the next move?

**Comment by bredamc** [comment]
@jseseCCS Are you happy to create the PR, or would you prefer for someone else to create it?

**Comment by jseseCCS** [comment]
thanks, @bredamc! i'd be grateful if someone who has the bandwidth (<-- gack! hate that term!) could do it, but if everyone is slammed, i will knock it out ASAP.

**Comment by bredamc** [comment]
No worries, Jocelyn -- I'll create it for you :)

**Comment by bredamc** [comment]
PR #328 is ready for review :)

**Comment by jseseCCS** [comment]
that's it. i'm coming to :ireland:, @bredamc!!

https://media.giphy.com/media/KvAKXViNfpU8fSDiF0/giphy.gif
