### ISSUE TITLE
Add clickable links to SSG section headings

### ISSUE THREAD

**Issue by bergerhoffer** [redhat-documentation/supplementary-style-guide#324]
Let's enable an easier way to get the links for headings in the SSG. There are two easy ways to do this in AsciiDoc (see https://docs.asciidoctor.org/asciidoc/latest/sections/title-links/).

Option 1: Character over hover
Preview (internal): http://file.rdu.redhat.com/~ahoffer/2023/main-sectanchors-char.html

Option 2: Make titles links
Preview (internal): http://file.rdu.redhat.com/~ahoffer/2023/main-sectlinks.html

If we go with option 1, there is already a PR open for it: #321

**Limitation**
Because we use the [discrete] tag above our glossary entries (to suppress them from showing in the TOC), this won't work for their headings. AFAIK we can't get this to work on glossary entry headings without removing the [discrete] tag (which we don't want to do because we don't want them to show up in the TOC). But if anyone else knows of a workaround for this, please share!

**Comment by aireilly** [comment]
There is a trade off here - the TOC levels are reduced. IMO it's an acceptable tradeoff. Section anchors are really useful for reviews.

**Comment by aireilly** [comment]
The Suggested alternative fix in https://github.com/redhat-documentation/supplementary-style-guide/pull/332 has been updated based on a conversation with @bergerhoffer PTAL

**Comment by joaedwar** [comment]
@bergerhoffer is this a duplicate issue. Is this addressed in the PR that was merged yesterday for the [discrete] tags?

**Comment by aireilly** [comment]
I think this can be closed as fixed :)
