### ISSUE TITLE
Add brief reason for using nbsp in "Red Hat" 

### ISSUE THREAD

**Issue by sbmetz** [redhat-documentation/supplementary-style-guide#326]
SSG survey response questioned the guideline to use a non-breaking space in "Red Hat". There are legal and/or branding reasons why we want to keep this guideline. Can we add a succinct reason to the SSG entry?

I haven't found a clear explanation about trademark or company name rules. Some references:

* Stylepedia's entry on [Using Company...Names Correctly](https://stylepedia.net/style/6.0/#product-names) implies that there are "restrictions" around how company and product names are used, and about breaking such names across lines. (The next section is about non-breaking spaces, but is still explanation-free.) Is "restrictions apply" sufficient? I'd like to know more.

* The [company trademark page](https://www.redhat.com/en/about/trademark-guidelines-and-policies) looked promising, but is mostly about how external parties use Red Hat and product names. (The branding content on the Source covers how to use the logos and points here.)

**Comment by bergerhoffer** [comment]
Per the 31 May SSG meeting, we will add a basic "for branding reasons". 

@sbmetz are you up for creating this PR, or would you like to see if someone else can take it?

**Comment by mportman12** [comment]
June SSG meeting outcome: Spank clarified that nbsps are necessary to prevent company names from being broken up across multiple lines. @spank50 to create PR to add reason for nbsp.

**Comment by mportman12** [comment]
@spank50 Can you create a PR for this?

**Comment by spank50** [comment]
This work was completed a couple of weeks ago.

**Comment by mportman12** [comment]
@spank50 Thanks! Closing this issue then.
