### ISSUE TITLE
Add "excludelist" to the suggested alternatives for "blacklist and whitelist"

### ISSUE THREAD

**Issue by jafiala** [redhat-documentation/supplementary-style-guide#330]
[blacklist and whitelist](https://redhat-documentation.github.io/supplementary-style-guide/#conscious-language) contains suggestions for "blocklist" and "denylist", but no standard wording of "excludelist".

I suggest adding "excludelist" to this section to unify the wording. For example, the RHEL repo curently contains both "exclude list" and "excludelist".

Of course, this only applies in situations where we must use a word like this and not write around these terms, as suggested as a first option in our style guides. And also only in cases where the other terms (blocklist, denylist) are not preferred.

**Comment by mportman12** [comment]
Some context: All use cases of "exclude list" are in situations where it is being used as a synonym for "blocklist" and "denylist". All use cases of "excludelist" are as a replaceable variable for a file name. For example:

> Replace `excludelist` with the path to the exclude list file.

While there is definitely a discussion to be had about adding "exclude list" to the SSG glossary, there aren't any issues (at least in RHEL) about the spelling.

**Comment by mportman12** [comment]
Also, the SSG section finishes with this:

> You can also use a term that has been agreed by your product team stakeholders.

This allows for further flexibility based on team and product preferences, so I don't think we need to be super prescriptive here. If there was an issue with "excludelist"/"exclude list" being used interchangeably, then I'd see a use case for adding a glossary entry to clarify the correct spelling. But that isn't an issue on RHEL.

**Comment by bredamc** [comment]
Agreed at the SSG meeting today:

- We will create glossary terms for "excludelist" and "exclude list" to ensure consistent usage.
- We will not update the "Conscious language" section because the final bullet point already covers additional preferences.

**Comment by bburt-rh** [comment]
I guess we'll leave this one on hold until @bredamc returns. She already has a PR for it.

**Comment by bergerhoffer** [comment]
We didn't get a chance to discuss this at the 30 August meeting. We'll have to revisit at next month's meeting to decide whether to go with one word or two words as the recommendation.

**Comment by bredamc** [comment]
Agreed at the CCS meeting today that this term is already covered by the following sentence in the SSG:
"You can also use a term that has been agreed by your product team stakeholders."

So we will not add the term. Closing this issue and the related PR.
