### ISSUE TITLE
Survey results to do

### ISSUE THREAD

**Issue by mportman12** [redhat-documentation/supplementary-style-guide#331]
We received a lot of feedback from the SSG survey. These are my TODO items:
- [x] Review SSG for sections that could be improved with examples.
- [x] Contact @aireilly about whether it's possible to add links to glossary entries (to discuss at May SSG meeting).
- [x] Add link to [FAQs: CCS style guides and term conventions](https://source.redhat.com/groups/public/ccs/ccs_wiki/ccs_style_guides_and_term_conventions#WhatGuide) to forum-ccs-style Slack channel heading.
- [x] Advertise [existing e-training](https://start.learning.redhat.com/totara/4624?externalUrl=https:%2F%2Flearning.redhat.com%2Frawcontent.php%3Ftarget%3Dhttps:%2F%2Flearning.redhat.com%2Fcourse%2Fview.php%3Fid%3D4624) on the style guides. 
- [x] Host Best Practices section on the style guides.

**Comment by aireilly** [comment]
Hi Miriam! Do you mean glossary entry links in Vale errors? Unfortunately this is not possible. We can only have one link per rule file. 
![image](https://github.com/redhat-documentation/supplementary-style-guide/assets/74046732/354deb7b-3c8d-4ab4-a8e4-a067181a2dd9)
So what we do is link to a Vale at Red Hat page, which links to SSG entries. Not ideal IMO. I would really like to see links to every entry in the SSG.
Example:
https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/termssuggestions/

**Comment by mportman12** [comment]
@aireilly Sorry for the confusion! No, I mean providing clickable links to glossary entries in the SSG itself. This is on the agenda meeting for tomorrow, so we can discuss further then. Andrea has a pretty good summary of the issues at play in [Issue 324](https://github.com/redhat-documentation/supplementary-style-guide/issues/324).

**Comment by aireilly** [comment]
Oh cool. This is already done in the new look and feel. demo: https://file.emea.redhat.com/aireilly/ssg_demo/#contractions

@bergerhoffer had asked me to PR these CSS updates. I need to do that.

**Comment by aireilly** [comment]
IMO, the correct thing to do here is remove the discrete tags altogether and remove the `image:images/yes.png[yes]` images from the section titles.
