### ISSUE TITLE
Add guidance on documenting features that have known issues

### ISSUE THREAD

**Issue by vikram-redhat** [redhat-documentation/supplementary-style-guide#34]
We don't seem to have an official guidance on documenting features in product docs and/or in release notes that have issues due to which those features may not work. If a reader is looking at documentation on a feature and the feature works but with bugs, should we:

* not document the feature at all since it doesn't work? OR...
* document the feature but link to the known issue from the feature docs and the release notes? OR...
* document the feature, make no note of the issue in the feature docs, and only document the issue in the release notes?

If we go with the middle option, should we have guidance on where we should note the bug within the concept, procedure or reference as may be the case.

**Comment by rkratky** [comment]
@vikram-redhat, I believe that's what the Known Issues doc is for. If a feature is included, but QE or others find a bug (that's not a blocker, i.e. the feature is not pulled, and the release goes ahead), then we document the problem (and possible workarounds) in Known Issues.

Adding notes about it into the doc itself would add undesirable overhead. (That is, of course, unless the "bug" is deemed just fine by the product team, in which case it's not considered a bug -- then we need to write the docs "around" the bad design/implementation.)

**Comment by vikram-redhat** [comment]
> @vikram-redhat, I believe that's what the Known Issues doc is for. If a feature is included, but QE or others find a bug (that's not a blocker, i.e. the feature is not pulled, and the release goes ahead), then we document the problem (and possible workarounds) in Known Issues.
> 
> Adding notes about it into the doc itself would add undesirable overhead. (That is, of course, unless the "bug" is deemed just fine by the product team, in which case it's not considered a bug -- then we need to write the docs "around" the bad design/implementation.)

Cool. I think you are saying that the third option that I listed is the correct one to follow in this case. 

Should we note this in this guide so that we can have a consistent usage for this use case across our product docs?

**Comment by rkratky** [comment]
> Cool. I think you are saying that the third option that I listed is the correct one to follow in this case.

Yes.

> Should we note this in this guide so that we can have a consistent usage for this use case across our product docs?

I suppose... Which brings to mind what I perceive as a general lack of CCS-wide guidance about release notes (and known issues). Every team (and product) uses a different approach, so there's no consistency in the amount of content, structuring, or formatting. Not to mention that all RH release notes look ugly and boring compared to what's out there :(

**Comment by vikram-redhat** [comment]
> I suppose... Which brings to mind what I perceive as a general lack of CCS-wide guidance about release notes (and known issues). Every team (and product) uses a different approach, so there's no consistency in the amount of content, structuring, or formatting. Not to mention that all RH release notes look ugly and boring compared to what's out there :(

Agreed - perhaps this could be the step in making another attempt to standardize. :)

**Comment by bergerhoffer** [comment]
I feel like there were a few folks in CCS who worked on defining standards for release notes, but I can't think of who it was. I'd be interested in hearing thoughts from them on this.

@IngridT1 or @redhat-documentation/ccs-style-council does anyone know who/what I might be thinking of?

I can see value to including the known issue/workaround directly in the affect doc procedures, etc., but can see how that could be a maintenance issue. So I'm not sure what the right answer is here.

**Comment by leswilliams44** [comment]
@bergerhoffer, When I worked on .NETCore, I used known issues within the release notes. I also based what I did on the RHEL release notes. I think Jirka Hermann may have a pretty good approach to release notes because he coordinates them for all the RHEL subsystems team, or at least that's my understanding.

**Comment by stoobie** [comment]
@bergerhoffer Isn't PR 22 [1] what you're referring to? @ndeevy implemented these guidelines.

[1] https://github.com/redhat-documentation/supplementary-style-guide/pull/22

**Comment by bergerhoffer** [comment]
@stoobie No, that's just guidance for doc text. I thought I remembered something in mojo or a Google doc or something that people in CCS put together a few years back for more overall release notes guidelines. But I might be misremembering.

**Comment by stoobie** [comment]
@bergerhoffer I don't know what it's like on your product, but in RHV and RHEL and I thought most products, if not all, then the Doc text field in Bugzilla is the place where you write the release note, and define what kind it is: bug fix, known issue, etc.

Here's the summary text/outline from the article that @ndeevy wrote more than a year ago on Mojo (now the Source): 

> A doc text is a short description of an engineering Bugzilla or Jira issue that is published in product Errata Advisories and Release Notes.
It includes:
* Enhancements
* Bug Fixes
* Known Issues
* Tech Preview
* Deprecated Features
* Remove Notice

Isn't this what you're talking about?

**Comment by bergerhoffer** [comment]
@stoobie I understand what you're getting at, but no, that's not what I'm thinking of. I think there was some other document/effort around release notes, which is what I'm seeing if anyone else remembers something else like that.

**Comment by cbudz** [comment]
@bergerhoffer @stoobie - I recall there being some discussion or effort on a comprehensive release notes strategy. @leswilliams44 can you tap content strategy to see if anyone there is clued in on this or familiar with any effort?

**Comment by leswilliams44** [comment]
@cbudz, will do

**Comment by ndeevy** [comment]
> @bergerhoffer @stoobie - I recall there being some discussion or effort on a comprehensive release notes strategy. @leswilliams44 can you tap content strategy to see if anyone there is clued in on this or familiar with any effort?

Hi @bergerhoffer, I'm going to send you two links on the Style Council google chat about some team-specific release notes guidance that was discussed a few months ago.

**Comment by IngridT1** [comment]
Sorry to be late to the party. I think that @naciao might know something about that. I would normally go look on Mojo for what I'm thinking about, but am not sure that it's made it to The Source yet.

**Comment by inoxx03** [comment]
> @bergerhoffer @stoobie - I recall there being some discussion or effort on a comprehensive release notes strategy. @leswilliams44 can you tap content strategy to see if anyone there is clued in on this or familiar with any effort?

Do you by any chance mean the [Middleware Release Notes Consistency Project](https://docs.google.com/presentation/d/15mZr-sK8If5Jvzmm9cMXBzjB5vwaRagsK5mQ7eWbr9M/edit#slide=id.g5c4c4a1d02_0_74)?

The project reached Phase 1 in Mid-2019 and was led by @sjay72 if I rememember correctly.

If this is a moot point already, then I'm sorry for the spam, but I hope that the information I found helps.

**Comment by leswilliams44** [comment]
Hi, @vikram-redhat and @bergerhoffer. Do we have any updates for this issue?

**Comment by mportman12** [comment]
@bergerhoffer @vikram-redhat There hasn't been any progress on this issue for nearly a year. I vote we either table it as on hold, or close the issue without resolution at this point.

**Comment by bergerhoffer** [comment]
Yeah I honestly don't know if we're going to find a good resolution for this, so I'm okay to close it. @vikram-redhat Let us know if this is still something that we need to pursue and we can reopen.
