### ISSUE TITLE
The supplementary SG uses "recreate" while the IBM SG requires "re-create"

### ISSUE THREAD

**Issue by mramendi** [redhat-documentation/supplementary-style-guide#342]
The IBM Style Guide says on page 380:

re-create verb
Use “re-create,” which refers to creating again, not “recreate,” which refers to taking recreation.

The supplementary SG does not explicitly override the IBM SG on this word so I assume the IBM SG is binding. But the supplementary SG fails to follow it in the following places:

https://redhat-documentation.github.io/supplementary-style-guide/#release-notes-doc-texts in an example text:

Before this update, the loopback device for Cinder iSCSI/LVM backend was not recreated after a system restart, which prevented the cinder-volume service from restarting. With this update, a systemd service recreates the loopback device and the Cinder iSCSI/LVM backend persists after a restart.

https://redhat-documentation.github.io/supplementary-style-guide/#_p in "pod"

Description: In Kubernetes, a pod is a set of one or more containers deployed together to act as if they are on a single host, sharing an internal IP, ports, and local storage. OpenShift Container Platform treats pods as immutable. Any changes to the underlying image, Pod configuration, or environment variable values, cause new pods to be created and phase out the existing pods. Being immutable also means that any state is not maintained between pods when they are recreated. The API object for a pod is Pod.

**Comment by bergerhoffer** [comment]
+1, these instances of "recreate" are incorrect and we should fix them. Good catch!

@mramendi let me know if you have any interest in submitting a PR to changes these instances of "recreate" to "re-create", or if you'd like one of our project members to take care of it. Thanks!

**Comment by bergerhoffer** [comment]
No problem at all! 

@redhat-documentation/ccs-style-council Anyone have a few minutes to submit a PR for this simple fix?

**Comment by dfitzmau** [comment]
Hi, @bergerhoffer . I've not contributed to the SG in some time, I'll take on this update.
