### ISSUE TITLE
Clarify markup for UI elements that do not have a tooltip or label

### ISSUE THREAD

**Issue by apinnick** [redhat-documentation/supplementary-style-guide#347]
Section to update: [UI Elements](https://redhat-documentation.github.io/supplementary-style-guide/#user-interface-elements)

> Bold all graphical user interface elements, including, but not limited to, menu names, menu items, button names, dialog box names, and window names. Bold the item, even if it is not clickable.

I recommend adding a sentence to clarify markup and capitalization for UI elements that do not have a tooltip or label. The current text could mean that a search field, for example, should be bolded. Same applies to icons.

Which is correct?
- **Search** field
- **search** field
- search field

**Comment by bburt-rh** [comment]
I agree with @bergerhoffer that if the actual text doesn't appear in the UI then it should not be bolded or capitalized (or capitalized only if referring to a proper noun).

The current IBM style guidance for UI fields does not cover cases where there is no label or tooltip for the field: https://www.ibm.com/docs/en/ibm-style?topic=elements-ui#field.

I would be in favor of adding guidance for this use case to https://redhat-documentation.github.io/supplementary-style-guide/#user-interface-elements: something like, "when no label, tooltip, or other identifying text exists for a field, make a generic reference to it. For example, if a search field contains no label or tool tip, refer to it as `the search field`."

**Comment by bredamc** [comment]
I think this item is already covered in the _UI elements_ topic in _IBM Style_. See the _icon_ entry in the usage table:

If an icon opens a menu, refer to the icon by its label, followed by icon. 
Example: 
_For an icon with the label **Actions** that opens a menu:_
Click the **Actions** icon.

If an icon does not have a label or tooltip, refer to the icon by a generic description.
Example: 
Click the print icon.

**Comment by bergerhoffer** [comment]
@bredamc thanks for sharing that. Though since we do override the ISG's guidance on how to style UI elements (we just bold everything instead of getting particular depending on the element), I think we should also mention this in our section in the SSG? Does that sound okay to you?

**Comment by bredamc** [comment]
Ah my apologies, I misunderstood the intention! Yes, absolutely -- thanks, @bergerhoffer!

**Comment by mportman12** [comment]
@bergerhoffer makes a good point about our UI guidance. I think this deserves a sentence to note that we align with the ISG on this.

**Comment by bergerhoffer** [comment]
I can work on a draft PR for this

**Comment by bergerhoffer** [comment]
All - I have a PR up, please take a look and let me know what feedback you have. Thanks!

https://github.com/redhat-documentation/supplementary-style-guide/pull/349
