### ISSUE TITLE
Add Minimalism guidelines to the Supplementary Style Guide?

### ISSUE THREAD

**Issue by IngridT1** [redhat-documentation/supplementary-style-guide#355]
@bergerhoffer suggested that we either add minimalism guidelines to the SSG or link to a separate guide. I need to discuss this issue with the Minimalism Steering Committee next month. But it's a great idea.

**Comment by mportman12** [comment]
I will create a PR for this.

**Comment by mportman12** [comment]
Created [PR](https://github.com/redhat-documentation/supplementary-style-guide/pull/370).
