### ISSUE TITLE
Add index for ELB

### ISSUE THREAD

**Issue by dfitzmau** [redhat-documentation/supplementary-style-guide#361]
I've had to address an [OCP docs bugs](https://issues.redhat.com/browse/OCPBUGS-8097) where the full term expansion of ELB was stated as "Elastic Load Balancer" when in fact "Elastic Load Balancing" is the correct expansion. Maybe this issue is too specific, but I raised it because of the variation on fully expanded ELB across the OCP documentation.

I was in contact with an AWS Technical Writer who confirmed the correct terminology. 

ELB supports numerous load balancers: Application, Network, Gateway, and Classic. I see abbreviations for these load balancers among various online sources; however, Amazon does not explicitly abbreviate them. See/Read:

- https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/introduction.html
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html
- https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html
- https://docs.aws.amazon.com/elasticloadbalancing/latest/gateway/introduction.html

Perhaps added a sentence to the ELB index would clarify that ELB supports these load balancers?

**Comment by mportman12** [comment]
@dfitzmau There's nothing about ELBs in the SSG currently, but this certainly seems like a good glossary candidate. Would you be able to create a PR for this and add an entry?

**Comment by dfitzmau** [comment]
Thanks, @mportman12 . I'll raise a PR next week to add this term to the SSG.
