### ISSUE TITLE
Ingress definition

### ISSUE THREAD

**Issue by skrthomas** [redhat-documentation/supplementary-style-guide#366]
Should we clarify that ingress can also refer to incoming traffic (like egress and ingress traffic), and in that case its lowercase, as opposed to Ingress resources, which are capitalized?

**Comment by skrthomas** [comment]
https://redhat-documentation.github.io/supplementary-style-guide/#ingress

**Comment by mportman12** [comment]
@skrthomas Based on the context, I think it would be useful to add a sentence to the Ingress entry to note the non-capitalized usage. Could you open a PR for this?

**Comment by skrthomas** [comment]
@mportman12 Yep, I can do that :) will post my PR here in the comments.

**Comment by bergerhoffer** [comment]
@skrthomas I remember there being something different about "ingress", but I'm still not sure if I understand why "Ingress" is capitalized sometimes. I think it makes sense when it's the "Ingress Controller", but not just by itself. (I know it's listed capitali in the OCP glossary too, but that seems wrong to me

If it's the Ingress resource, then I would think it should be marked up as the `Ingress` resource, just like all of our other API objects on OpenShift. And then be lowercase for any general references.

In that case, shouldn't the entry just be lowercase "ingress" then? Like "config map" [1] and "pod" [2]?

[1] https://redhat-documentation.github.io/supplementary-style-guide/#config-map
[2] https://redhat-documentation.github.io/supplementary-style-guide/#pod

**Comment by skrthomas** [comment]
@bergerhoffer I've always thought that when you're referring to an Ingress API resource, like the Ingress Controller, you capitalize. But if you're describing the direction of traffic, then ingress is lowercase. 

But yea, I agree, since my entry is not talking about the resource, I should lowercase it like the other entries you referenced.

**Comment by skrthomas** [comment]
@bergerhoffer sorry, I realize that my entry is lowercase. 

My whole reason for submitting this is because from time to time, I have to talk about ingress traffic in the Network Observability documentation where there's a UI and you have visibility of ingress and egress traffic. Sometimes I get peer review questions wondering if I should capitalize it, pointing to the current SSG Ingress definition, which only defines the noun. So I was thinking that I could clarify this confusion by adding an entry for the ingress adjective, which describes the directional flow of network traffic vs the Ingress resource which can be used to control that flow.

**Comment by bergerhoffer** [comment]
@skrthomas I think what's confusing is the fact that the ingress entry in the SSG is capitalized, and that's what needs to just be changed to lowercase.

**Comment by skrthomas** [comment]
@bergerhoffer Ohhh, I see. I think that entry is correct because it basically defines this: https://kubernetes.io/docs/concepts/services-networking/ingress/ - The Ingress API object/resource, noun. What is unclear (to me) is the other, adjective form of ingress which just describes the incoming network traffic.

**Comment by bergerhoffer** [comment]
@skrthomas as far as i'm aware, "Ingress" is the only object that seems to have a special capitalized entry. Do you refer to "Ingress" capitalized in the doc without marking it up as `Ingress`? 

The "pod" entry describes what a pod is, but is lowercase. We don't have a capitalized "Pod" entry to show that you need to capitalize when you're referring to the actual `Pod` resource. That's just part of our API object formatting rules for OCP. I would think the same should apply for "ingress". Also as a similar example to ingress, route is lowercase: https://redhat-documentation.github.io/supplementary-style-guide/#route

**Comment by skrthomas** [comment]
@bergerhoffer Ah, well that's interesting and an important distinction to notice. Hmm...I'm not sure _why_ that's the case. There are a few instances in https://docs.openshift.com/container-platform/4.10/networking/ingress-operator.html where "Ingress" is capitalized and not marked up as `Ingress` and some cases even where Ingress Controller isn't marked up 😬 ...these are not specifically things I've created. This doc has been around for a while and had a few contributors.

 In the _Ingress configuration asset_ topic, there's a few confusing non-marked-up/capitalized instances and it creates some uncertainty about whether the text is referencing ingress traffic or the Ingress resource. For example,
>This `Ingress` resource defines the cluster-wide configuration for Ingress. 
I *think* this should be:
>"The `Ingress` resource defines the cluster-wide configuration for ingress traffic. 

The Ingress Operator is capitalized and not marked up, but that just follows Operator standards. 

Specifically the case I've worked on recently is here: https://docs.openshift.com/container-platform/4.10/networking/network_observability/network-observability-network-policy.html where I describe the need for having a network policy to secure ingress traffic and its lowercase.

**Comment by bburt-rh** [comment]
@skrthomas What's the current status of this issue? Can you please provide an update? Thanks!

**Comment by skrthomas** [comment]
@bburt-rh Thanks for re-surfacing this to me. It dropped off my radar as release work picked up. Its still relevant just need to polish it based on feedback from Andrea and hopefully it can be approved.

**Comment by bergerhoffer** [comment]
Closing because #368 was merged
