### ISSUE TITLE
Why "Pulldown" instead of "Dropdown"

### ISSUE THREAD

**Issue by stoobie** [redhat-documentation/supplementary-style-guide#376]
I'm curious to understand why the word *Pulldown* was chosen over *Dropdown* for menus that open when you click on them? Both IBM Carbon and Google style guides recommend using *Dropdown* or *Drop-down*.

* https://carbondesignsystem.com/components/dropdown/usage/
* https://developers.google.com/style/word-list#drop-down

**Comment by bergerhoffer** [comment]
So, I tracked this glossary entry down to the initial population of the old glossary of terms and conventions project, which initially populated the entries from stylepedia in 2016. In 2017 it looks like stylepedia changed their guidance to not use "pulldown".

I don't see any reason why we would need to recommend "pulldown" over what IBM style recommends ("pulldown" = no; "pull-down" = with caution; "drop-down" and "dropdown" = with caution"). 

I'd recommend that we remove this entry and follow IBM style's guidance. @redhat-documentation/ccs-style-council thoughts?

**Comment by IngridT1** [comment]
Yes, "drop-down" or "dropdown" makes a lot more sense. I agree, @bergerhoffer

**Comment by bburt-rh** [comment]
Assigning to myself to put together a PR

**Comment by dfitzmau** [comment]
In relation to OCP, "drop-down" or dropdown" are more common terms than "pulldown". Examples from vendor platforms that support OCP:

* https://cloud.google.com/resource-manager/docs/creating-managing-projects
* https://aws.amazon.com/blogs/mt/use-aws-systems-manager-automation-to-create-input-parameters-that-populate-aws-resources-as-a-dropdown-list/
* https://docs.vmware.com/en/VMware-SD-WAN/3.3/VMware-SD-WAN-by-VeloCloud-Administration-Guide/GUID-72FFBBA4-562E-4510-9281-F9320AE7EE8F.html

**Comment by bergerhoffer** [comment]
Noting that the decision was to just remove our "pulldown" entry. We will follow the IBM Style guide's guidance of using dropdown/drop-down

**Comment by bergerhoffer** [comment]
@bburt-rh Can you submit a PR for this when you get a chance?

**Comment by bburt-rh** [comment]
@bergerhoffer and @IngridT1 - I created #403 to remove the "pulldown" entry from the glossary. Please review

**Comment by bburt-rh** [comment]
@bergerhoffer and @IngridT1 - PR #404 is ready for review.
