### ISSUE TITLE
Add "inject" to the glossary?

### ISSUE THREAD

**Issue by jseseCCS** [redhat-documentation/supplementary-style-guide#377]
Hi, y'all! Another one for discussion:

My UX teammates and I were doing a microcopy working session the other day, and we all wondered about a developer's use of the verb "inject." We all know it's commonly used, what it means, etc., but it's one of those words that just gives pause to folks like us. KWIM? Worth adding to our SSG?

**Comment by bergerhoffer** [comment]
I don't see any reason why we couldn't add it to the SSG as a valid word to use (in the right contexts) if it would help writers who hesitate on it.

**Comment by mportman12** [comment]
Sounds good! @jseseCCS please create a PR for this when you have time.

**Comment by bburt-rh** [comment]
@jseseCCS - Can you be sure to link your PR to this issue when ready? Thank you!

**Comment by jseseCCS** [comment]
> @jseseCCS - Can you be sure to link your PR to this issue when ready? Thank you!

doing this now. thanks for the nudge/reminder to link PR!

**Comment by jseseCCS** [comment]
@bburt-rh @mportman12 and others, here's my PR. def need editorial help here. couldn't get perspective on this one. thanks!

[PR 388](https://github.com/redhat-documentation/supplementary-style-guide/pull/388)

**Comment by mportman12** [comment]
PR is merged, so closing issue.

**Comment by jseseCCS** [comment]
thanks so much, @mportman12!
