### ISSUE TITLE
Add guidance on interpreter directives

### ISSUE THREAD

**Issue by jhradilek** [redhat-documentation/supplementary-style-guide#381]
Neither the IBM Style Guide nor Red Hat Supplementary Style Guide provide any guidance on how to refer to Linux interpreter directives such as `#!/bin/bash`. A quick google search shows that Red Hat documentation oscillates between "shebang" ([173 results](https://www.google.com/search?q=site%3Aaccess.redhat.com%2Fdocumentation+%22shebangs%3F%22)), "hashbang" ([1020 results](https://www.google.com/search?q=site%3Aaccess.redhat.com%2Fdocumentation+%22hashbangs%3F%22)), and "interpreter directive" ([193 results](https://www.google.com/search?q=site%3Aaccess.redhat.com%2Fdocumentation+%22interpreter+directives%3F%22)).

**Comment by mportman12** [comment]
The Wikipedia article for this concept uses [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)).

**Comment by bburt-rh** [comment]
The Aug 29th meeting of the Style council proposed the following 3 new entries:

- _Shebang_ and _interpreter directive_, use with each other at least on first use
- _hashbang_, do not use

**Comment by mportman12** [comment]
Sorry for the delays on this. I'll try to get started on this in the next week.

**Comment by bergerhoffer** [comment]
Closing because #432 was merged.
