### ISSUE TITLE
RPM, rpm-ostree, OSTree

### ISSUE THREAD

**Issue by ShaunaDiaz** [redhat-documentation/supplementary-style-guide#383]
We use RHEL for Edge in MicroShift, so I was looking for guidance on styles for these terms. I'm uncertain why we cap "RPM" and "OSTree" but lowercase the two together, for  the "rpm-ostree" system. I submit that it is more consistent to use "RPM-OSTree" in documentation when writing it out.

**Comment by mportman12** [comment]
I searched the RHEL docs repo, and it looks like most mentions of rpm-ostree have it formatted in backticks. This indicates that they want to keep the formatting lowercase with the hyphen to match the file/repo/package/etc. names. With Andrea's Google research, it seems like this is a term that customers expect to be seen spelled lowercase with a hyphen. I don't think we should change our style guide recommendation.

**Comment by ShaunaDiaz** [comment]
At the least, our guidance should include the backticks. To really conform to the RHEL for Edge docs, as you suggest here, we would need to make our guidance  "RHEL for Edge (rpm-ostree)," which is how it is there. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/composing_installing_and_managing_rhel_for_edge_images/introducing-rhel-for-edge-images_composing-installing-managing-rhel-for-edge-images

**Comment by bburt-rh** [comment]
Per the style council meeting, @mportman12 will create a PR for the changes we decided on in the meeting.

**Comment by bergerhoffer** [comment]
Mentioning that the decision was to go with "rpm-ostree" lowercase and in backticks

**Comment by bergerhoffer** [comment]
Closing - #415 was merged
