### ISSUE TITLE
Standardize on capitalizations for Red Hat Customer Portal and its short forms

### ISSUE THREAD

**Issue by IngridT1** [redhat-documentation/supplementary-style-guide#384]
I thought the standard capitalizations for the Customer Portal were like this:
- Red Hat Customer Portal (initial caps)
- Customer Portal (initial caps)
- portal (lowercase)

But the current SSG has this entry:
[Red Hat Customer Portal (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#red-hat-customer-portal)
Description: Red Hat Customer Portal is the official name of the customer portal at https://access.redhat.com/.
Use it: yes
Incorrect forms: Customer Portal

The Corporate Style Guide says this and uses initial caps for "Customer Portal":

> Customer Portal
> These terms are used in the context of the Red Hat Customer Portal:
> Customer Case Management
> Customer-centric Support
> Developer Support
> Solutions (Internal only: Knowledge-Centered Support (KCS), KCS Solutions)
> Knowledgebase Articles
> Red Hat Discussions / discussions (lowercase when used alone)
> Support 

Case
https://source.redhat.com/groups/public/word-nerds/red_hat_word_nerds_wiki/corporate_style_guide#c

@bergerhoffer says we've never discussed this in a meeting, so the SSG entry might not actually be a CCS standard.

**Comment by bburt-rh** [comment]
Putting this one on hold for now. We ran out of time while discussing this issue in the last council meeting and did not chart a course of action, if any.

**Comment by bergerhoffer** [comment]
I don't think we need to put this on hold. We can continue discussion here in the issue or pick it up at next month's meeting.

We didn't finish discussing at the meeting, but did determine that we likely don't want to use just "the portal". I think the next thing we want to discuss is whether to also allow "Customer Portal" instead of always having to write out the "Red Hat Customer Portal".

**Comment by mportman12** [comment]
Did not have time to discuss at September Style Council meeting.

**Comment by bergerhoffer** [comment]
Result of the October SSG meeting: We are good with using "Customer Portal", with "Red Hat Customer Portal" on first use. We did not want to use just "the portal".

@mportman12 I believe you volunteered for this one, but let me know if we should ask for any other volunteers for this one to spread the work.

**Comment by mportman12** [comment]
@bergerhoffer If someone else has capacity, they could probably get to it sooner than I can.
