### ISSUE TITLE
Establish clearer guidelines for command highlighting in code blocks

### ISSUE THREAD

**Issue by jherrman** [redhat-documentation/supplementary-style-guide#390]
The mark-up of commands in code blocks is currently inconsistent across Red Hat documentation: 

- Some RH docs use bolded commands, with non-bolded output: [Example](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_virtualization/cloning-virtual-machines_configuring-and-managing-virtualization#preparing-a-virtual-machine-template_assembly_creating-virtual-machine-templates)

- Some RH docs use non-bolded commands and output: [Example](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_file_systems/mounting-nfs-shares_managing-file-systems#discovering-nfs-exports_mounting-nfs-shares) 

- OpenShift documentation uses bold commands in code blocks, with examples in separate code block, also in bold: [Example](https://docs.openshift.com/container-platform/4.10/post_installation_configuration/machine-configuration-tasks.html#machine-config-drift-detection_post-install-machine-configuration-tasks)

- ^However, this seems to be a result of different stylesheets on the OpenShift docs site. [The same content on the RH Customer Portal](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/post-installation_configuration/post-install-machine-configuration-tasks#machine-config-drift-detection_post-install-machine-configuration-tasks) is not in bold.

There likely are other variations within our docs set as well. As a result, this creates a rather disjointed reader experience, especially given that code blocks with commands are often the most important parts of our procedures.

This may be partly because our style guides do not really give clear directions about this:

- IBM Style states that command names should be in bold monospace: https://www.ibm.com/docs/en/ibm-style?topic=format-highlighting 

- IBM Style states that commands entered on the CLI should be in (just) monospace: “When you tell users to run, type, enter, or issue a command on a command line or at a command prompt, use a monospaced font for the command name.” - https://www.ibm.com/docs/en/ibm-style?topic=elements-commands

- The RH SSG does not determine either way, but uses examples with non-bolded code-blocks: https://redhat-documentation.github.io/supplementary-style-guide/#user-replaced-values 

Therefore, I would like to propose recommending (but not necessarily mandating) a specific unified style for code block mark-up. My preference would be the first one I listed - bolded commands, with non-bolded output in the same code block.

- Visual differentiation of commands is very useful for readability and scannability of our procedures. Given that our current stylesheets render code blocks as light-grey, a more prominent styling for the command characters would distinguish them nicely from both the lead-in text and the output.

- The copy-paste button feature on the Customer Portal seems to be able to filter away the output, so keeping it in the same code block as command examples does not have a functional downside and saves on “screen real estate”.

- Making this approach non-mandatory provides leeway for situations when it would not be optimal - for instance when only a specific segment of a command or a part of the output should be emphasised. Optionally, callouts can be used for highlighting in code blocks instead.

**Comment by bergerhoffer** [comment]
> Well, I would recommend that the style guide strongly encourages one command per code block and one code block per step. 

Great, that makes sense to me too.

@redhat-documentation/ccs-style-council other thoughts on this issue?

**Comment by dfitzmau** [comment]
I agree, too. This was a rule often followed in the Runtimes space. There is one exception: using the backslash (escape character) to stop the shell from interpreting the shell so that one can input a large set of commands as one input. 

Screenshot taken from https://docs.openshift.com/container-platform/4.10/post_installation_configuration/node-tasks.html

![Screenshot from 2023-09-11 16-02-04](https://github.com/redhat-documentation/supplementary-style-guide/assets/57954076/6dc55e77-f507-407e-bbbe-033e182faa23)

**Comment by jherrman** [comment]
@dfitzmau , multi-line commands like this require adding asterisks in the markup on each of the lines, but functionally, they seem to work well in our docs. On the Customer Portal at least, the copy/paste button can "consume" such a multi-line command as a whole, and pasting the command into the terminal does not trigger any of the lines separately.

For testing, see for instance https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_and_managing_virtualization/assembly_creating-virtual-machines_configuring-and-managing-virtualization#creating-virtual-machines-using-the-command-line-interface_assembly_creating-virtual-machines

**Comment by jherrman** [comment]
Based on the discussion in today's Style Council meeting, I will be creating a PR for this change to be implemented in the Supplementary Style Guide.

**Comment by jherrman** [comment]
Created a PR with the updates at https://github.com/redhat-documentation/supplementary-style-guide/pull/413

@bergerhoffer @dfitzmau or anyone else, feel free to review and let me know if it looks ship-shape.

Cheers,
J.

**Comment by rolfedh** [comment]
I wonder if using _subs quotes_ might occasionally mangle some legit command input or output that happens to contain [words that are incidentally enclosed by AsciiDoc formatting syntax.](https://docs.asciidoctor.org/asciidoc/latest/subs/quotes/#table-quotes-html)

I created [a python script to find some instances like this](https://github.com/rolfedh/pythontools/blob/main/find-quote-patterns.py) but don't quite have the regex chops to pull it off.

**Comment by jherrman** [comment]
> I wonder if using _subs quotes_ might occasionally mangle some legit command input or output that happens to contain [words that are incidentally enclosed by AsciiDoc formatting syntax.](https://docs.asciidoctor.org/asciidoc/latest/subs/quotes/#table-quotes-html)

Yes, that can definitely happen, but usually can be fixed by `\escaping` one of the (not)asciidoc characters.

**Comment by rolfedh** [comment]
> can be fixed by `\escaping` one of the (not)asciidoc characters.

I wish we had tooling to ensure that writers would see when they need to do that.

**Comment by bergerhoffer** [comment]
Closing because PR #413 has been merged!
