### ISSUE TITLE
Add "Application" to Homographs

### ISSUE THREAD

**Issue by jafiala** [redhat-documentation/supplementary-style-guide#393]
I propose adding "Application" to the list of homographs, because this might actually be a rather common occurrence.

For example, just came across this sentence in a draft during peer review: "...choosing between application stability and application of security updates."

Also, while at it, let's capitalize all items in the Homographs list to be compliant with [IBM Style (Capitalize the first word of each item in a vertical list.) ](https://www.ibm.com/docs/en/ibm-style?topic=format-lists#capitalization-in-lists)

**Comment by bergerhoffer** [comment]
No objections from me to add "Application" and to capitalize this list items.

@jafiala would you be able to open a PR for this?

**Comment by jafiala** [comment]
Done, please review: https://github.com/redhat-documentation/supplementary-style-guide/pull/394

**Comment by bergerhoffer** [comment]
Closing because PR #394 has been merged
