### ISSUE TITLE
Add entry and usage guideline for FedRAMP

### ISSUE THREAD

**Issue by spank50** [redhat-documentation/supplementary-style-guide#395]
FedRAMP is US gov't guideline for cloud security. 
https://en.wikipedia.org/wiki/FedRAMP

3Q23, Red Hat is qualifying Hybrid Cloud for FedRAMP.
Make sure we have guidelines for using FedRAMP (never FedRamp or other variation)

The gov't site indicates (r) for these names.
https://www.fedramp.gov/

The Federal Risk and Authorization Management Program (FedRAMP®) provides a standardized approach to security authorizations for Cloud Service Offerings.

**Comment by spank50** [comment]
Hybrid Cloud Console and Insights are the initial focus for FedRAMP delivery - issue was raised at the HCC supplemental style group meeting on 09/18/23 with a recommendation to move ahead.

**Comment by bergerhoffer** [comment]
@spank50 This is just asking to add a glossary entry for "FedRAMP" right? If that's the case, then I think you're probably safe to open up a PR if you're up for it

**Comment by bredamc** [comment]
I think this issue was closed prematurely, the original PR was closed as a duplicate, the info is not yet in the SSG.
