### ISSUE TITLE
Proposal to update term "binary executable file" to "executable" in supplementary style guidelines and Vale rules

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/supplementary-style-guide#396]
**Description**:

The term `executable` is commonly used and understood among our customers and contributors. 
Currently, the supplementary style guide uses the term "binary executable file" and IBM Style states: ![image](https://github.com/redhat-documentation/supplementary-style-guide/assets/350907/7e2cb351-c8e5-4dd7-b525-d02f4234ba39).

**Problem Statement**:

- Enforcement of the term "binary executable file" or similar alternatives consumes unnecessary time.
- Enforcing use of the longer term diminishes goodwill among contributors.
- Like "GPS", the term "executable" is clear, concise, and widely understood without expansion.

**Proposed Solution**:

Update the supplementary style guidelines and Vale rules to allow the use of the term `executable` as an acceptable alternative to "binary executable file."

**Justification**:

1. Simplifies terminology without sacrificing clarity.
2. Enhances user experience by using commonly understood terms.
3. Saves time for both contributors and reviewers.

**Action Items**:

1. Modify the supplementary style guide to include `executable` as an accepted term.
2. Update Vale rules to accommodate this change.
3. Communicate the update to all contributors and reviewers.

By implementing this change, we can streamline the contribution process and enhance readability.

**Comment by michelle-purcell** [comment]
+1 @rolfedh - Executable (noun form) is extremely widely used and seems to be preferred by developer audiences within Red Hat, our technology partners, and competitors. Thanks for raising this :+1:

**Comment by mportman12** [comment]
Discussed at the September Style Council meeting. Decided that we should write out “binary executable file (executable)” on first use and then just “executable” after that. 
@rolfedh Can you create a PR for this?

**Comment by mportman12** [comment]
PR has been merged, closing this issue.
