### ISSUE TITLE
Add links to technical diagram resources

### ISSUE THREAD

**Issue by dfitzmau** [redhat-documentation/supplementary-style-guide#400]
Technical diagrams are an interesting visual element that can simplify a complex conceptual written topic. A lot of discussion is happening around providing more visual elements to our documentation (videos, and so on). Of course, visual elements have their own maintenance overhead. 

I recently struggled to find the link for the Technical Diagram Request Form on the Source, so would it be worthwhile to create a "Diagrams" subsection that resides under the [Graphical interface](https://redhat-documentation.github.io/supplementary-style-guide/#graphical-interfaces) section of the SSG. This subsection could provide useful links and some guidance around diagram use? I personally think that this is a good way to consolidate diagram resources in a common writer resource (the SSG).

Jess sent me the following useful links:

* https://source.redhat.com/groups/public/diagrams
* https://customer-platform.pages.redhat.com/documentation-svg-assets/index.html
* https://docs.google.com/forms/d/e/1FAIpQLSdF8V0n3E-aAfRen8vZchXCxwA0iDTd0QYyASnutznfGLATvA/viewform

**Comment by dfitzmau** [comment]
@redhat-documentation/ccs-style-council WDYT?

**Comment by bergerhoffer** [comment]
@dfitzmau Unfortunately I don't think we'd be able to do this. The SSG is a public resource and these links look to be internal.

We might be able to provide some generic information mentioning that all diagrams should be done by our graphic designers. But probably no direct links.

**Comment by dfitzmau** [comment]
Thanks, @bergerhoffer . That make sense. Only solution would be to create a separate private repo, which is just another maintenance burden. 

I'll request an update to the OCP Docs Manual.
