### ISSUE TITLE
Add guidance for redacting long code output

### ISSUE THREAD

**Issue by jafiala** [redhat-documentation/supplementary-style-guide#401]
Code output is often very verbose and parts of it are not relevant to the user's current task. To omit the irrelevant parts, we redact the output by using "...", but we don't have this codified. This means new writers must ask, and the standard is only passed on by tradition. We should add explicit guidance, probably to [Long code examples](https://redhat-documentation.github.io/supplementary-style-guide/#long-code-examples).

[Example 1](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/security_hardening/index#ref_troubleshooting-problems-related-to-pc-sc-and-polkit_assembly_controlling-access-to-smart-cards-using-polkit)
[Example 2](https://access.redhat.com/documentation/en-us/red_hat_satellite/6.12/html-single/managing_content/index#Managing_Custom_File_Type_Content_content-management)
[Example 3](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/configuring_basic_system_settings/index)
[Example 4](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/configuring_and_managing_networking/index#configuring-the-rate-limiting-of-packets-by-using-the-tc-ctinfo-utility_linux-traffic-control)

**Comment by bergerhoffer** [comment]
IBM's [Code and command examples](https://www.ibm.com/docs/en/ibm-style?topic=elements-code-command-examples) page uses "..." to truncate examples, but doesn't explicitly state to use them.

I think this would be good to add to the SSG.

We also have additional guidance on OpenShift for truncating YAML examples that we might want to consider also including. Basically, `...` has a meaning in the YAML language (end of document marker), so we comment them out as `# ...` (to make the YAML valid / not confuse with the end of document marker)

**Comment by mportman12** [comment]
Did not have time to discuss at September Style Council meeting.

**Comment by jafiala** [comment]
Discussed in the October Style Council meeting.

However, I just noticed [IBM already recommends](https://www.ibm.com/docs/en/ibm-style?topic=elements-code-command-examples) to "(u)se ellipses to omit parts of code snippets that do not contribute to the example you want to illustrate. To omit one or more lines of code, add an ellipsis to its own line."

With OpenShift already having its own guidance, I don't think it's necessary to add this to the SSG.
