### ISSUE TITLE
Add technical guidance on use of AsciiDoc character replacement subs

### ISSUE THREAD

**Issue by dfitzmau** [redhat-documentation/supplementary-style-guide#414]
RH products integrate with many third-party vendor products, so the use of registered trademark symbols and so on is sometimes required. 

Suggestion to add guidance on use of some of these character replacements with a link to https://docs.asciidoctor.org/asciidoc/latest/subs/replacements/ .

**Comment by dfitzmau** [comment]
I won't move on this work until https://github.com/openshift/openshift-docs/pull/67220 is merged

**Comment by mportman12** [comment]
Discussed at the November Style Council meeting: Not sure if the SSG would be the right place for this, unless we had a section already on trademark symbols. Perhaps AsciiDoc writing guide could be the right place. Or wait and see if we add any guidance to the SSG on trademark symbols.
