### ISSUE TITLE
Revise deprecation notice guidance to require PM approval for mentioning specific deprecation release numbers

### ISSUE THREAD

**Issue by bburt-rh** [redhat-documentation/supplementary-style-guide#420]
In general, [our guidance for mentioning specific future releases or specific release dates](https://redhat-documentation.github.io/supplementary-style-guide/#statements-about-the-future) is clear: avoid doing it.

However, we do make an exception for deprecation notices. This exception has led to some confusion and much discussion about what is allowable when we mention deprecation plans for a future release. 

To alleviate this confusion, @skrthomas suggested that the SSG officially recommend that we require PM approval in the PR if it's necessary in the PR to cite a specific version for a deprecation notice. 

Let's use this issue to discuss the pros and cons of making such a recommendation or requirement.

**Comment by skrthomas** [comment]
Pro: The current exception contradicts clear, explicit statement to avoid referencing future releases. IMO, this creates a sweaty decision for reviewers and writers. It seems that the red light turns to green, but as we discovered today in our peer-review-squad private thread, feeling _good_ about referencing a future release is hard. If we have a recommendation in the hands of PM, then it makes the red light turn more to a yellow light, "use with caution", which seems more appropriate than the drastic switch from "Do not do this" to "you can do it in this case".

Con: We have to bother PM for something else besides change management. Not sure how big of a deal this is but PMs are busy ppl and sometimes hard to get ACKs in PRs. But maybe this will lead to further yielding and ultimately the decision to use more general, non-commital language about a "future release"

**Comment by mportman12** [comment]
Discussed at the November Style Council meeting: Requiring writers to discuss with PMs is too detailed, as this would not necessarily be the approval process for all teams. @bburt-rh  to draft a PR to update this future release section to give more guidance on deprecations.

**Comment by Srivaralakshmi** [comment]
@bburt-rh Any updates on this PR about updating this future release section to give more guidance on deprecations?
