### ISSUE TITLE
I vote that we longer use "look-up". Let's standardize on lookup for adjective or noun.

### ISSUE THREAD

**Issue by IngridT1** [redhat-documentation/supplementary-style-guide#422]
The Corporate Style Guide and stylepedia.net are making an entry to use "lookup" as an "adjective" or "noun", "look up" for a verb. IBM Style does not have an entry. Let's keep ourselves aligned with these two guides and stop using "look-up".

https://docs.google.com/spreadsheets/d/1Go2vvHoLMT5JtrO-Z-oFJIkMZl_9QJGGYsm0o2Wgl7o/edit#gid=0

**Comment by bergerhoffer** [comment]
No objections from me based on my few minutes of Googling.

**Comment by bredamc** [comment]
Can we ask for the term to be added to IBM Style instead of SSG?

**Comment by mportman12** [comment]
Discussed at the November Style Council meeting: Remove all lookup/look-up/look up entries and defer to Merriem-Webster. @bredamc to open a PR to remove these entries.
