### ISSUE TITLE
Add guidance to avoid using "now" and "previously" in release notes

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/supplementary-style-guide#426]
Based on [an internal Slack thread](https://redhat-internal.slack.com/archives/C0218RXJK5E/p1700680787534569), we should add guidance to the word list to avoid using "now" and "previously" in release notes.

**Comment by rolfedh** [comment]
@jhradilek@redhat.com

**Comment by jhradilek** [comment]
Thank you so much for working on this, @rolfedh. I reviewed the pull request and the explanation looks good to me.

**Comment by mportman12** [comment]
Discussed at the November Style Council meeting: Team didn’t all necessarily agree with this. This might have been inferred guidance from Vale by what examples are given in the release notes section of the SSG.
@bergerhoffer and @rolfedh to follow up with @ndeevy, who authored the release notes section, on whether she has any history on this from when she wrote that section.

**Comment by rolfedh** [comment]
@mportman12. Thanks for the follow up note. 

For background, please see [this Slack thread](https://redhat-internal.slack.com/archives/C0218RXJK5E/p1701170553926069?thread_ts=1700680787.534569&cid=C0218RXJK5E) in the #proj-vale-at-red-hat. 

There, for example, I explained:
![image](https://github.com/redhat-documentation/supplementary-style-guide/assets/350907/c7b3ad15-1cb3-4db5-a7fa-d8d44e16f532)

And @ndeevy commented:
![image](https://github.com/redhat-documentation/supplementary-style-guide/assets/350907/882a9739-e5d3-4d4b-ad21-47f6879e4162)

**Comment by rolfedh** [comment]
@mportman12 I reworded the proposed changes in https://github.com/redhat-documentation/supplementary-style-guide/pull/425 so that the guidance applies only to product teams who have adopted the templates from the SSG release notes section.
