### ISSUE TITLE
Review and updated temporal language for known issues?

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/supplementary-style-guide#428]
In https://github.com/redhat-documentation/supplementary-style-guide/pull/425, @bergerhoffer raised the following point:

"Added some feedback but I'd also like to ask more about the "now" guidance. And whether this also applies to "currently", which is similar to "now". The examples in the release notes section for known issues use "currently".

The "before this update" replacement for "now" works for fixed bugs, but not for known issues. Should we provide a suggested now/currently replacement for known issues? Something like "As of this release" or similar?"

**Comment by rolfedh** [comment]
https://redhat-documentation.github.io/supplementary-style-guide/#_known_issue

**Comment by Srivaralakshmi** [comment]
@redhat-documentation/ccs-style-council Need your feedback and response to [this question](https://github.com/redhat-documentation/supplementary-style-guide/issues/428#issue-2016567558). Please help. TY!

**Comment by mportman12** [comment]
Discussed at the January Style Council meeting. Outcome: Create an entry for “currently” and define it as being used when the described situation will change in the future. @lburcher7 to create PR.

**Comment by bburt-rh** [comment]
@lburcher7 - what's the current status of your PR for this issue? Thanks!

**Comment by lburcher7** [comment]
@bburt-rh Thanks for the reminder. I have a draft and will submit a PR tomorrow morning at the latest.
