### ISSUE TITLE
Plugin or plug-in + Styleguide overrides.

### ISSUE THREAD

**Issue by gfialova** [redhat-documentation/supplementary-style-guide#436]
Dear all, 

I am filing an issue to tackle a discrepancy between styleguides:

While it's **plug-in** according to the IBM SG, the Supplementary styleguide says **plugin**.

This is also related to the issue of instances where the Supplementary Styleguide overrides the IBM styleguide.
In the Supplementary styleguide, there is a section "How to Use This Guide" at the beginning. This section says that "the Supplementary styleguide **overrides certain guidance** of the IBM styleguide. But which guidance? How do you decide?

I know for a fact that this causes much confusion among writers and we need to clarify the styleguide overrides.

Thank you.

![Screenshot from 2024-01-11 10-34-53](https://github.com/redhat-documentation/supplementary-style-guide/assets/84566568/7a0b37da-32b3-436c-95a5-6909f12862a8)

**Comment by bburt-rh** [comment]
Thanks for writing up this issue. I'm not clear exactly what issue you and other writers are having with the wording of the guidance for "plugin" vs "plug-in"? Would you mind clarifying more specifically what is confusing writers about this guidance? Maybe provide some specific examples or instances in which writers have been confused?

Thanks!

**Comment by bergerhoffer** [comment]
@gfialova - As @bburt-rh mentions, anything in the SSG takes precedence the IBM Style. Is it the word "certain" in that statement that is causing confusion?

I think "certain" is in there because some of the items in the RHSSG are completely new and not covered in the ISG at all, but there are some items that exist both places, and in those cases is where the SSG overrides the ISG.

Happy to update this statement to make it clearer, if needed. Let us know!

**Comment by Srivaralakshmi** [comment]
@gfialova PTAL at [this comment ](https://github.com/redhat-documentation/supplementary-style-guide/issues/436#issuecomment-1898808155)and respond. TY!

**Comment by mportman12** [comment]
Discussed at the January Style Council meeting. Outcome: Rewrite the sentence "When looking for style guidance, reference this guide first, because it overrides certain guidance from the IBM Style guide." to make it clearer what the relationship is between SSG and ISG. @bburt-rh to create PR.
