### ISSUE TITLE
Standardize our nomenclature for use/usage/instance/occurence/mention of a term

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/supplementary-style-guide#438]
We use a variety of terminology when talking about the instances of a term. Here's an example wordcount of "first" followed by any other "instance"-like term:

'first use': 16
'first usage': 12
'first instance': 10
'first occurrence': 5
'first mention': 5
'first time': 4
'first reference': 3

Having a standard term might improve clarity and enable us to establish common patterns for saying similar things.

**Comment by bergerhoffer** [comment]
No objections to standardizing this. 

I looked at the ISG, and they use "on first occurrence" most (13) followed by "on first use" (3) and just one "on first reference".

Since it's already our leading term, and it is used a little in the ISG, I vote for using "on first use". I also think it sounds the most natural.

**Comment by rolfedh** [comment]
```
Results for "first use" in "supplementary-style-guide/*.adoc"

/home/rdlugyhe/supplementary-style-guide/GUIDELINES.adoc:
  139:  ** Spell out "comma-separated values" on first use; use "CSV" thereafter.


/home/rdlugyhe/supplementary-style-guide/supplementary_style_guide/glossary_terms_conventions/general_conventions/b.adoc:
  96:  On first use, use "Basic HTTP authentication"; thereafter, use "Basic authentication".


/home/rdlugyhe/supplementary-style-guide/supplementary_style_guide/glossary_terms_conventions/general_conventions/c.adoc:
  41:  DHCP, DNS, and TFTP. Use the two-word name on first use in a section; the single term 'Capsule' is acceptable
  486:  value is separated by a comma. Spell out "comma-separated values" on first use; use "CSV" thereafter.
  557:  Content Views. Use the three-word name in full on first use in a section; the abbreviation "CCV" is acceptable
  746:  intelligent filtering. Use the two-word name in full on first use in a section; the abbreviation "CV" is acceptable


/home/rdlugyhe/supplementary-style-guide/supplementary_style_guide/glossary_terms_conventions/general_conventions/d.adoc:
  207:  deliberately and with malicious intent. Use "denial of service (DoS)" on first use and "DoS" thereafter.


/home/rdlugyhe/supplementary-style-guide/supplementary_style_guide/glossary_terms_conventions/general_conventions/e.adoc:
  198:  specific operations based on its coded instructions. Write "executable file (executable)" on the first use.


/home/rdlugyhe/supplementary-style-guide/supplementary_style_guide/glossary_terms_conventions/general_conventions/l.adoc:
  236:  physical machines, they can communicate with each other. Logical partitioning was first used in 1976 by IBM.


/home/rdlugyhe/supplementary-style-guide/supplementary_style_guide/glossary_terms_conventions/general_conventions/r.adoc:
  438:  enterprise-grade Java application server. Spell out on first use in a guide, and use the approved abbreviation "JBoss
  559:  *Description*: On first use in a module, use the complete product name and the abbreviation in parentheses


/home/rdlugyhe/supplementary-style-guide/supplementary_style_guide/glossary_terms_conventions/general_conventions/s.adoc:
  66:  Linux-based infrastructure. Use the two-word name on first use in a section; the single term "Satellite" is acceptable
  1184:  Satellite 6. Use the two-word name in full on first use in a section; the word "manifest" is acceptable
  1252:  Sybase Adaptive Server Enterprise (ASE)" on the first use; on subsequent mentions, use "Sybase ASE". If discussing


/home/rdlugyhe/supplementary-style-guide/supplementary_style_guide/glossary_terms_conventions/general_conventions/w.adoc:
  81:  to the web. If necessary, spell out web UI on first use. Do not hyphenate the abbreviation or use the one-word

```

**Comment by rolfedh** [comment]
Thanks for highlighting the usage patterns in our documentation and the ISG. Standardizing on 'first use' fits well with our current practices and sounds quite natural. Building upon this, I'd like to suggest a few refinements:
While 'first use' is clear and concise, there are instances where repeating 'use' in a sentence poses a stylistic challenge. For example, in the phrase 'On first use, use "Basic HTTP authentication"', the duplication could be slightly awkward. To enhance readability and accessibility, we could either insert the definite article, making it 'on the first use.'
What do you think?

**Comment by bergerhoffer** [comment]
Good points @rolfedh.

Having "first use" right against "use" is definitely not desirable. However, I don't think that inserting "the" in there solves it. I'd recommend that we don't start the sentence "On first use," so we don't run into this problem. Most of the places do something like "Write <x> on first use" or "Spell out <x> on first use" or "Use <x> on first use". Even though the last one is better than right next to each other, I think a word other than "use" would be preferable.

That being said, we could still consider adding "the" in there. My main concern is that it might actually not sound correct. I'm thinking that "on first use" is a more common way to phrase it. Let me know if you think we should try to pursue adding "the", and if so, we can get some more opinions on it!

**Comment by rolfedh** [comment]
Later this week, I'll return to the draft PR I created earlier today and replace instances of "use" (verb) with "write" or "spell out". Although one could make significant revisions to "parallelize" these types of constructions throughout the guide, that task is outside the scope of this issue.

**Comment by rolfedh** [comment]
@bergerhoffer What do you think about the modifications in this second commit? 
https://github.com/redhat-documentation/supplementary-style-guide/pull/439/commits/16ef908aebcedaf16fb622b5b5e1cf5a0f39a331

**Comment by Srivaralakshmi** [comment]
@bergerhoffer Can you please respond to [this comment](https://github.com/redhat-documentation/supplementary-style-guide/issues/438#issuecomment-1908823135)? TY!

**Comment by rolfedh** [comment]
> @bergerhoffer Can you please respond to [this comment](https://github.com/redhat-documentation/supplementary-style-guide/issues/438#issuecomment-1908823135)? TY!

Thanks for asking, @Srivaralakshmi. @bergerhoffer is away this week. She and I will continue our collaboration on this when she returns.

**Comment by bburt-rh** [comment]
@bergerhoffer and @rolfedh - Can you please update this issue with a current status? Thanks!

**Comment by rolfedh** [comment]
Hi @bburt-rh,

Thank you for your inquiry regarding this issue and its associated PR, #439. The PR is currently pending a review and needs a minor update before merging. I will promptly notify you through this issue when it has been resolved.
