### ISSUE TITLE
Remove RHV content

### ISSUE THREAD

**Issue by apinnick** [redhat-documentation/supplementary-style-guide#446]
Red Hat Virtualization is in [maintenance support](https://access.redhat.com/support/policy/updates/rhev/) until August 2024. The downstream documentation is no longer maintained. I think it would be safe to remove RHV terms:

- [Administration Portal (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#administration-portal)
- [collect (verb)](https://redhat-documentation.github.io/supplementary-style-guide/#collect)
- [Data Warehouse (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#data-warehouse)
- [details view (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#details-view) - Make this generic, like the OpenShift Virt VM [details view](https://docs.openshift.com/container-platform/4.15/virt/getting_started/virt-web-console-overview.html#virtualmachine-details-page_virt-web-console-overview). I think ISG refers to this as a **Details** page, not a details view.
- [header bar (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#header-bar) - Remove RHV. Perhaps substitute the Hybrid Cloud Console.
- [host (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#host-rhv)
- [Manager virtual machine (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#manager-virtual-machine)
- [MOM (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#mom)
- [Monitoring Portal (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#monitoring_portal)
- [Red Hat Enterprise Linux host (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#red-hat-enterprise-linux-host) - Maybe the term is still used by other products.
- [Red Hat Virtualization (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#red-hat-virtualization)
- [Red Hat Virtualization Host (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#red-hat-virtualization-host)
- [Red Hat Virtualization Manager (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#red-hat-virtualization-manager)
- [resource tab (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#resource-tab) - this is weird. I wonder why this specific tab was included.
- [results list (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#results-list) - also strange
- [self-hosted engine (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#self-hosted-engine)
- [self-hosted engine node (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#self-hosted-engine-node)
- [sparse (adjective)](https://redhat-documentation.github.io/supplementary-style-guide/#sparse)
- [sparsify (verb)](https://redhat-documentation.github.io/supplementary-style-guide/#sparsify)
- [standalone Manager (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#standalone-manager)
- [Storage Pool Manager (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#storage-pool-manager)
- [sub-version (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#sub-version)
- [sysprep (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#sysprep) - You can change RHV to OpenShift Virtualization, which does support [sysprep](https://docs.openshift.com/container-platform/4.15/virt/getting_started/virt-web-console-overview.html#virtualmachine-details-initial-run_virt-web-console-overview).
- [VM Portal (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#vm-portal)

**Comment by bburt-rh** [comment]
@apinnick - Thanks for the heads up about this. Would you have the time to submit a PR that removes these items from the glossary? If not, lmk, and I can take this one on. Thanks again.

**Comment by apinnick** [comment]
I guess so....

**Comment by apinnick** [comment]
It's a yes. I created a PR.

**Comment by apinnick** [comment]
@bburt-rh PR is ready for review
