### ISSUE TITLE
The personhood of users

### ISSUE THREAD

**Issue by jafiala** [redhat-documentation/supplementary-style-guide#466]
Summary: I propose to add guidance for cases when the word "user" does not signify a person, and then it should use inanimate pronouns.

IBM Style advises to distinguish between persons and non-persons for relative pronouns (_who_ vs. _that_ and _which_) and personal pronouns (sg. _they_ vs. _it_).

In Linux, we often refer to "users" that are not persons but effectively "user accounts": For example, Linux users such as root, SELinux users such as `user_u`. In fact, one person may have multiple Linux users on the same system, and a SELinux user is an identifier of one or multiple Linux users for access control purposes.

Therefore, in these specific cases, the word "user" does not signify a person so should not be referred to with "who" but with "that" or "which".

Adding the guidance would make it easier to more consistently distinguish between the general use of "user" and the technical use of "user", which should help our readers to more easily understand the information.

Compare:

**Personal use:**
"Experienced _users who_ can configure their own systems..."
"_Users who_ want to install their own packages..."

**Non-personal use:**
"Therefore, a Linux _user_ has the restrictions of the SELinux _user to which it_ is assigned." (two in one!)

"removes a _user that_ exists outside the IdM domain"

"By convention, SELinux _users that_ are generic have the suffix "_u", such as user_u. "

"Pass the `-U _<user_name>_` parameter to the command to specify a _user that_ is allowed to perform the requested action."

**Comment by sbmetz** [comment]
If it's generally clear (to the writer) whether it's a person vs a service account, I think this is a nice enhancement that I would appreciate as a reader. (I'm not sure that all readers will get the nuance, but I like it.) That being said -- is it always clear? Do we want to offer guidance if it's not clear, such as a default choice, or a workaround/write-around?

**Comment by jafiala** [comment]
Sure, I think we should decribe typical usage. For example, if we're talking about file ownership, access privileges, and UIDs, the users are inanimate. In most other cases, like users of tools, users entering passwords, and other general cases, users are animate.

So probably default choice would be animate, unless the writer knows they write about users in the technical sense.

And I would typically default to not write about users, but for users - so instead of "For users who are experienced, ..." something like "If you are an experienced user,...".

**Comment by mportman12** [comment]
Discussed at the June Style Council meeting. Write around, if not possible use “user that” and make sure it is clear this is not a human-related user.
@jafiala please create a PR for this.

**Comment by jafiala** [comment]
Created MR: https://github.com/redhat-documentation/supplementary-style-guide/pull/495
