### ISSUE TITLE
Not italicizing user-replaced variables

### ISSUE THREAD

**Issue by apinnick** [redhat-documentation/supplementary-style-guide#47]
https://redhat-documentation.github.io/supplementary-style-guide/#user-replaced-values

I recommend that user-replaced variables not be italicized because the markup and rendering can be very messy if a code block or CLI example contains strings that begin with `__`. 

See Vladimir Slavik's on my blog post, [AsciiDoc Workarounds](https://source.redhat.com/personal_blogs/asciidoc_workarounds).

**Comment by bergerhoffer** [comment]
@apinnick I agree that there are some places where italicizing can be more complicated, but as far as I'm aware, I haven't come across anything that hasn't been able to be solved with a workaround.

**Comment by bergerhoffer** [comment]
@apinnick Unless you have any further objections, I'm going to close this issue.

The new 2020 version of the IBM style guide actually has more guidance on replaceable values, and using angle brackets with italics. 

> If it is likely that a user will paste a variable value from the documentation into a location that does not support an italic font, such as a command line or script, you can enclose the variable in angle brackets. Angle brackets can make it easier for users to identify variables that must be replaced where an italic font is not supported. Apply the italic font to both the angle brackets and the variable. 
> ...
> db2 BACKUP DATABASE _<database_alias>_ USER _\<username>_ USING _\<password>_ TO _<backup_directory>_ 

So I think we have the right idea with our current guidance.
