### ISSUE TITLE
Revisit guidance for only using "disconnected"

### ISSUE THREAD

**Issue by ShaunaDiaz** [redhat-documentation/supplementary-style-guide#471]
Current guidance instructs using "disconnected" for all cases where clusters operate without network connectivity. However, the MicroShift engineering team rejects this guidance as failing to capture the nuance of edge devices. This is also confusing for customers who are used to seeing the word in the context of _restricted networks_.

Disconnected = no Internet connection is present, i.e. device is running on a private network without Internet access
Offline = no network connection is present, i.e. all network cards unplugged

Most the the core OCP docs talk about disconnected or air-gapped devices in the latter context [example](https://docs.openshift.com/container-platform/4.15/operators/admin/olm-restricted-networks.html). With the proliferation of edge devices that are running self-contained clusters and have no network cards at all, we should revisit the topic. 

Suggestion is to add "offline" for edge-device cases.

Examples of terms in use: https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.15/html/installing/microshift-embed-in-rpm-ostree-for-offline-use 
And here we have "fully disconnected" because we didn't use the term "offline": https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.15/html/networking/microshift-disconnected-network-config

In these cases, there is no internet AND no network for truly _**offline**_ scenarios.

**Comment by ShaunaDiaz** [comment]
@snarayan-redhat We aren't talking about oc mirror or any other instance of mirroring here. We are discussing a completely self-contained cluster deployed on something like a drone, a robot arm, or other edge device that never connects. See, "Offline = no network connection is present, i.e. all network cards unplugged." I don't think adding adjectives to "disconnected" is the best solution for either minimalism or clarity of the use case.

**Comment by snarayan-redhat** [comment]
@ShaunaDiaz The link was not to point to the mirroring stuff but to give you a reference to the terminologies that are currently used in other pieces of documentation. I agree that having separate terms for different types of disconnected modes 

AFAIU, we still haven't blacklisted the other terms like "offline" and is still open to use sparingly. But as you pointed out, it is indeed worth revisiting to have some clarity around using these terms since guideline seem to convey that they all are synonymous.

**Comment by ShaunaDiaz** [comment]
Summarizing discussion and action point from 5 Jun 2024 CCS Style Guide meeting: We agreed that MicroShift can have an exception to use both "offline" and "disconnected" as appropriate. Further, we agreed that adding "offline" to the Supplementary Style Guide (SSG) should be done to socialize the use throughout the docs teams. @bredamc Noted that "offline" is already in used elsewhere as well, so we need to be aware of those cases. We can refine the definition here and then create a PR to add the final term and definition to the SSG. 

Term/Definition starting proposal (please review and add thoughts):
Offline - Use for endpoints where no network connection is present and/or all network cards are unplugged. Examples include edge devices in physically remote locations.

**Comment by ShaunaDiaz** [comment]
We should also update the entry for "disconnected" to remove "offline" cases and point to this new definition.

**Comment by bergerhoffer** [comment]
Closing because #489 was merged
