### ISSUE TITLE
Create a list of initialisms/acronyms that writers do not need to spell out at first use?

### ISSUE THREAD

**Issue by jseseCCS** [redhat-documentation/supplementary-style-guide#477]
There doesn't seem to be one place where writers can quickly check whether an initialism or acronym is common enough that we don't need to spell it out at first use. Terms like these:

- CLI
- SSO
- UI (The [IBM SG addresses this one](https://www.ibm.com/docs/en/ibm-style?topic=word-usage), but maybe we at RH can choose to add it to such a list as the one I'm proposing here.)

I think we should create such a list, either in The Source, as a Confluence page, as a new section in our SSG...? Thoughts?

**Comment by mportman12** [comment]
Discussed at the June Style Council meeting. Outcome: This might be a bit too difficult, because you have to take the audience into account when determining whether to spell out on first use or not.
