### ISSUE TITLE
Update the existing on-premise entry to expand OCP support

### ISSUE THREAD

**Issue by dfitzmau** [redhat-documentation/supplementary-style-guide#485]
The "on-premise" term in the RH SSG is marked as a use-with-caution term: https://redhat-documentation.github.io/supplementary-style-guide/#on-premise

This marking is valid in certain context with the exception of OpenShift where "on-premise" can refer to a bundle of platforms (bare metal, vSphere, Nutanix, and OpenStack).

The purpose of this issue is to add an exception to the existing `on-premise` guidance for OpenShift.

**Comment by bergerhoffer** [comment]
Outcome from the 5 June SSG meeting was to add a line to the current on-premise entry to cover this product-specific situation

**Comment by dfitzmau** [comment]
PR #501 merged so I'm closing this PR.
