### ISSUE TITLE
Add names for UI elements

### ISSUE THREAD

**Issue by bergerhoffer** [redhat-documentation/supplementary-style-guide#49]
We should add entries for what to call these two UI elements, known (informally?) as a hamburger button and kebab icon:

**Hamburger button**
<img src="https://user-images.githubusercontent.com/7443887/101533139-79075000-3963-11eb-857a-4aa9d11eb3e9.png" width="25" height="25">

**Kebab icon**
<img src="https://user-images.githubusercontent.com/7443887/101533457-d8656000-3963-11eb-9fc9-a12040f6ed8e.png" width="25" height="25">

I don't think that either of these terms are appropriate for technical docs, and I've seen this come up a few times across CCS, so we should add in guidance.

What I've seen at least for the kebab, is calling it the "Options menu" and then putting an image of the icon afterward. For example:

> Click the Options menu <img src="https://user-images.githubusercontent.com/7443887/101533457-d8656000-3963-11eb-9fc9-a12040f6ed8e.png" width="12" height="12"> and ...

Not sure if "Options menu" is always appropriate, or maybe only if there is no tooltip. But a followup question on this is whether "Options" should be capitalized and/or styled bold like a UI item if it doesn't actually appear as a tooltip, or should it be lower/unstyled since it's not a literal value in the UI?

And is "menu" or "navigation menu" appropriate as a default for the hamburger button?

My first thoughts at guidance to propose:
* If the icon has a tooltip in the UI, use that as the name.
* If the icon doesn't have a tooltip, have a default name for it (TBD - menu / options menu?)
* Only capitalize/bold if the name actually appears as a tooltip on the icon in the UI
* Either way, include an image of the icon after the name for clarity.

Thoughts?

More info on the icons are here: https://en.wikipedia.org/wiki/Hamburger_button

**Comment by leswilliams44** [comment]
@bergerhoffer, I have also seen a "kebab" with the three dots aligned horizontally. I am not sure of the functional difference between the horizontal and vertical alignments.

**Comment by leswilliams44** [comment]
@bergerhoffer, Thanks for thinking about this issue. I agree with you that kebab and hamburger sound less than professional, and I think your proposal makes sense.

**Comment by bergerhoffer** [comment]
These two terms are now entries in the new 2020 version of the IBM style guide:

![image](https://user-images.githubusercontent.com/7443887/105228781-fa402e00-5b30-11eb-95eb-15ce78664eba.png)

![image](https://user-images.githubusercontent.com/7443887/105228849-104dee80-5b31-11eb-954f-14dc2a631f27.png)

I'm going to close this issue since it's already covered now. The only thing left might be whether or not to include the icon afterward or not, but probably not a big enough deal to worry about.
