### ISSUE TITLE
Additional guidance on Technology Preview release notes

### ISSUE THREAD

**Issue by mmuehlfeldRH** [redhat-documentation/supplementary-style-guide#491]
Currently, the [Technology Preview release notes](https://redhat-documentation.github.io/supplementary-style-guide/#_technology_preview) section in the SSG refers only to the [Technology Preview](https://redhat-documentation.github.io/supplementary-style-guide/#technology-preview-guidance) section.

I recommend that the Tech Preview RNs sections contains its own copy of the Tech Preview template - but without the first sentence. "<feature_name> is a Technology Preview feature only." doesn't fit in a chapter intro, and writers might replace it with a self-reference like "This section describes Technology Preview features in xyz" - which isn't compliant with IBM Style.

Additionally, the intro of a Tech Preview chapter in a release note document should not contain only an admonition with the template text ([example](https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2-latest/html/release_notes/technology-preview-features_relnotes)). It looks like something is missing (at least to me). The SSG should either suggest a specific intro sentence/paragraph in addition to the admontion with the template or mention that an introduction is needed in addition to the admonition.

**Comment by bergerhoffer** [comment]
Hi @mmuehlfeldRH. To answer your second point first, we actually have an open PR that should clarify this: https://github.com/redhat-documentation/supplementary-style-guide/pull/484

Basically this takes a stance that there should always be a lead-in sentence before you're adding an admonition. Feel free to comment on that PR if you feel it needs anything else.

As for your first part, I'm not sure if I understand. I don't like the idea of duplicating the TP template (for fear of it becoming outdated, though I guess we could try to use a snippet). But I also have not seen the need to use it outside of an admonition. Do you have an example of this usage that could help me understand more? The way I've seen the TP text used is always in an admonition (after some other sort of intro/explanation, etc.).

**Comment by bergerhoffer** [comment]
Thanks for that additional context and example @mmuehlfeldRH, that helps. 

We discussed this at today's SSG meeting. We don't necessarily want to duplicate it again elsewhere, but we agreed that we could add a note after the template stating that you can omit the first line if you are not talking about a specific feature. Hope this sounds like a good compromise that will give guidance to omit that first sentence instead of having people try to rewrite it.

@bburt-rh agreed to work on a PR for this.

**Comment by mmuehlfeldRH** [comment]
> We discussed this at today's SSG meeting. We don't necessarily want to duplicate it again elsewhere, but we agreed that we could add a note after the template stating that you can omit the first line if you are not talking about a specific feature.

Yes, that's a good solution. Thanks.
