### ISSUE TITLE
Boot loader vs. Bootloader

### ISSUE THREAD

**Issue by apinnick** [redhat-documentation/supplementary-style-guide#504]
Is there any justification for not allowing "bootloader"? It seems to be used as frequently as [boot loader](https://redhat-documentation.github.io/supplementary-style-guide/#boot-loader).

**Comment by tmalove** [comment]
> Is there any justification for not allowing "bootloader"? It seems to be used as frequently as [boot loader](https://redhat-documentation.github.io/supplementary-style-guide/#boot-loader).

@apinnick I just completed a PR where 'bootloader' was flagged and when I searched occurrences on the portal, I saw instances of the term as separate words. It would be good to have a standard for moving forward.

**Comment by apinnick** [comment]
I agree that we need to have a standard. Too bad that ISG does not provide any guidelines for this term.

**Comment by apinnick** [comment]
Just found something that might be relevant. It turns out that "boot loader" is short for "bootstrap loader", so that would be an argument for keeping the terms separate. In that case, I will close this issue.
