### ISSUE TITLE
RedHat.Symbols doesn't account for Markdown admonitions

### ISSUE THREAD

**Issue by donjuardo** [redhat-documentation/supplementary-style-guide#511]
For my `test.md` file:

```markdown
!!! note

    This is a note.

```

Vale with the RedHat style gives me:

```bash

 test.md
 1:1  suggestion  Do not use the '!' symbol.  RedHat.Symbols 
 1:2  suggestion  Do not use the '!' symbol.  RedHat.Symbols 
 1:3  suggestion  Do not use the '!' symbol.  RedHat.Symbols 

✔ 0 errors, 0 warnings and 3 suggestions in 1 file.

```

These suggestions are not syntax-aware of Markdown admonitions as in [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage).

**Comment by bergerhoffer** [comment]
Hi @donjuardo - the style guide doesn't manage Vale issues. Can you please open this issue against the Vale repo here: https://github.com/redhat-documentation/vale-at-red-hat

CC @redhat-documentation/vale-at-red-hat
