### ISSUE TITLE
Terms from EAP terminology and usage to add to other locations?

### ISSUE THREAD

**Issue by bobjohnsrh** [redhat-documentation/supplementary-style-guide#56]
While migrating the EAP terminology and usage content, I noticed several terms that might belong in other locations, mostly general conventions, but a few to specific other products.

- ActiveMQ, ActiveMQ Artemis (Add to AMQ module?)
- class loader, class loading, class path, CLASSPATH (Add to general conventions "C" module?)
- Customer Portal (Add to general conventions "C" module?)
- Java (Add to general conventions "J" module?)
- keystore (Add to general conventions "K" module?)
- load balance (Add general conventions "L" module?)
- Red Hat AMQ (Add to AMQ module?  Add to general conventions "R" module?)
- Red Hat Customer Portal (Add to general conventions "R" module?)
- trust store, truststore (Add to general conventions "T" module?

**Comment by bergerhoffer** [comment]
Closing, as EAP updates were recently revamped via #97.
