### ISSUE TITLE
Consider adding icons for the "Use it" field

### ISSUE THREAD

**Issue by bergerhoffer** [redhat-documentation/supplementary-style-guide#58]
We might want to consider adding icons for the "Use it" field. I feel like it can be easy to overlook that something is actually not supposed to be used. People might skim, find the entry, and not look at that field. I think that icons would make it more obvious to know the status of the term at a quick glance.

I feel like we might have discussed this in the past, but can't remember if we purposefully decided against it for some reason or not.

**Comment by gregraka** [comment]
Hi Andrea,

I'm not aware of this device in our docs. Would you mind pointing to an example?

Thanks,
--Greg

**Comment by bergerhoffer** [comment]
Sure! So we have the "Use it" field in our glossary for each entry. It can either be "yes", "no", or "with caution". Right now it looks like this:

![image](https://user-images.githubusercontent.com/7443887/109841419-067ed700-7c17-11eb-8b4e-d5a588f8b99a.png)

The IBM style guide uses an icon to indicate whether a term should be used or not (or with caution). Like below:

![image](https://user-images.githubusercontent.com/7443887/109841619-3af29300-7c17-11eb-8626-1a6f786e20ca.png)

Just wondering whether it was time that we did something similar, to make it jump out at users on whether terms should be used/not/with caution.

**Comment by gregraka** [comment]
@bergerhoffer I like the icons! +1

**Comment by bergerhoffer** [comment]
Decision at the May 5 project meeting was to move forward with this. I will look into this.

**Comment by bergerhoffer** [comment]
PRs have been merged to add the icons. Closing!
