### ISSUE TITLE
Single-step procedures at Red Hat deviate from IBM Style

### ISSUE THREAD

**Issue by IngridT1** [redhat-documentation/supplementary-style-guide#61]
The FCC Guidelines deviate from the IBM Style Guide on how we handle one-step procedures. Here are the IBM SG guidelines:

"If a procedure consists of only one step, present it as a sentence or short paragraph, and do not number it."

We should call this out in the Supplemental Style Guide and send people to the FCC guidelines.

**Comment by bergerhoffer** [comment]
Agree

**Comment by gregraka** [comment]
Hi,

The mod doc template for procedures goes a bit further by stating:
    "Use an unnumbered bullet (*) if the procedure includes only one step."
Perhaps the SSG should mention this, too?

**Comment by bergerhoffer** [comment]
Closing - PR #80 was merged.
