### ISSUE TITLE
Groups are spinning up to tackle how the new IBM SG changes our conversational tone, etc. 

### ISSUE THREAD

**Issue by IngridT1** [redhat-documentation/supplementary-style-guide#62]
How do we keep all these different groups in sync? Jennifer Ciroli, for example, wants to start a group about using less formal language. That seems to be something that we're already working on. At the very least, we need to coordinate with her, so that our recommendations are consistent.

What other groups are there?

**Comment by leswilliams44** [comment]
@IngridT1, Keeping people synced on standards is a big concern for me. Standards and best practices don't mean anything if people choose alternatives because they can.

**Comment by jhoyt-rh** [comment]
@leswilliams44 @IngridT1 I agree this is a concern -- 1. whether there needs to be another style group focusing on using less formal language, and 2.  how we get everybody on the same page about syncing the many styles and other standards. Seems to me it is difficult for writers, and especially writers new to Red Hat, to be aware of the plethora of style guides and initiatives. It's also an easy way to have conflicts, and once style  recommendations conflict, the end result is not much better than if we had none.

Jennifer's idea of starting a group to use less formal language does seem as if it might overlap (and might possibly contradict) what CCS is doing with regards to the Conscious Language initiative, plus Minimalism principles, especially as Ingrid's training sessions are tied to OKRs and are requirements for <most? all?> CCS writers.

Before too many folks initiate the formation of additional Style guides, I think we should put this on the agenda for discussion very soon.  I don't recall  discussing this in much detail in the past, but it seems we need to figure out our stance and also how we'll get the needed buy-in from CCS, and then get the information out there for all writers to comsume.

Can we please put it on our next agenda?

**Comment by bergerhoffer** [comment]
+1 definitely sounds like something that overlaps with our group and that we'd want to be involved or in sync with, if a group like that is warranted.

I can't say that I was aware that there were changes in recommendations for tone in the new ISG. So I'd be interested in hearing more on that. But I have to say that (without hearing more) I'd be hesitant to be less formal in the content we produce. Seems like being less formal would be more appropriate for marketing/product pages or learning apps for potential customers, as opposed to product documentation. But again, I don't have the background yet on what the intention/guidance is here.

I'll add it to this week's agenda, @IngridT1 if you (or someone who knows more about this subject) wouldn't mind bringing it up for discussion.

**Comment by IngridT1** [comment]
@bergerhoffer @leswilliams44 @cbudz @jhoyt-rh I talked to Jennifer Ciroli about this, and she said that she thinks her effort will actually just become part of Chris' Managed Services style guide. So that project, at least, is under control. Do we know of any others that have started?

**Comment by bergerhoffer** [comment]
Thanks for following up on this @IngridT1! I'm not personally aware of any others, outside of the managed services effort.

**Comment by bergerhoffer** [comment]
Closing this issue because there have been followups to check in with other teams that we know of who are working on style-related guidelines. And also a separate issue (#65) to define the conversational style.
