### ISSUE TITLE
The new IBM Style Guide recommends "lifecycle", but everything we have says "life cycle".

### ISSUE THREAD

**Issue by IngridT1** [redhat-documentation/supplementary-style-guide#69]
The old IBM Style Guide (2015) recommended "life cycle" for a noun (life-cycle as an adjective). This is also the standard for the Corporate Style Guide, the Customer Portal, and all of our legal docs around life cycle.

The new IBM Style Guide (2021) says "lifecycle". Now we need to add an exception the CCS supplemental style guide.

**Comment by leswilliams44** [comment]
It's common for two words to morph into one. Not my favorite trend, but it's happened as long as I can remember being interested in words and good scores on vocabulary tests. Life cycle vs. lifecycle is consistent with the word-morphing slide, similar to losing the hyphen after a prefix. I think it's more important that we differentiate between the noun and the adjective (life-cycle).

**Comment by IngridT1** [comment]
I actually prefer "lifecycle", because then non-native speakers don't have to worry about the distinction between noun and adjective. It's very confusing to explain to people. However, it would be a pain to change everything.

**Comment by bergerhoffer** [comment]
I've always preferred "lifecycle" as well. If we don't actually agree with "life cycle" two words, and don't feel like we have a good reason from deviating from the ISG, then I'm not sure that we should add an exception to the SSG.

The scope of our SSG is for product documentation, not for the entire company. I agree it's not great to have inconsistencies, but we can't control outside of CCS. Outside of bringing it up to word nerds to consider. But if we think that this inconsistency is a good enough reason to add the exception to the SSG, then so be it.

**Comment by bergerhoffer** [comment]
Decision from the May 5 project meeting - follow the IBM Style Guide's new guidance of "lifecycle". No action needed because no exception is needed for the SSG.
