### ISSUE TITLE
Clarify source of truth for different types of information

### ISSUE THREAD

**Issue by stoobie** [redhat-documentation/supplementary-style-guide#74]
Problem: We have three separate documents providing some overlapping information and conflicting guidance, and it is not clear to writers which document is the source of truth. The three documents are:

- The Mod Docs Reference
- The style guides (this one and the IBM Style Guide)
- The Asciidoc markup quick reference

To clarify which guide is the source of truth for what type of information, I propose we add the following disclaimer to all three guides. This issue is for this style guide. 

In an obvious place, add: 
_*NOTE* The link:https://redhat-documentation.github.io/asciidoc-markup-conventions/[AsciiDoc Mark-up Quick Reference] is the source of truth for guidance specific to writing in Asciidoc. The style guides, both the IBM Style Guide and the link:https://github.com/redhat-documentation/supplementary-style-guide/issues[Red Hat supplementary style guide] are the source of truth for output and writing style guidance that is not specific to Modular Documentation guidelines, and the link:https://redhat-documentation.github.io/modular-docs/[Modular Documentation Reference Guide] and templates are the source of truth for all things connected to Modular Documentation, including implementing those guidelines in Asciidoc._

**Comment by stoobie** [comment]
@rkratky @emmurphy1 @cbudz @bergerhoffer Please comment.

**Comment by bergerhoffer** [comment]
This sounds like a good idea to add to the guides. I would probably move the AsciiDoc markup guide last though, because I do think that any specifics for AsciiDoc in the mod docs guide would be more important than the general AsciiDoc guidance in there. Plus the mod docs guide gets updated/adjusted much more frequently, and the AsciiDoc guide can fall behind.

**Comment by cbudz** [comment]
@stoobie can you open a PR for this?

**Comment by mportman12** [comment]
@stoobie Reminder to open a PR for this :)

**Comment by bergerhoffer** [comment]
@stoobie can you draft this blurb with the related resources?

**Comment by bergerhoffer** [comment]
Closing since #128 was merged!
