### ISSUE TITLE
Allow or disallow contractions?

### ISSUE THREAD

**Issue by bergerhoffer** [redhat-documentation/supplementary-style-guide#79]
The new 2020 IBM style guide allows for contractions in technical documentation (the old version did not). We should consider adding an exception to the SSG to avoid contractions (unless we want to allow them).

Old IBM guidance:

> Do not use contractions in technical information.
> 
> Contractions can cause difficulty for translation and for users whose primary language is not English. For example, it’s can be interpreted as it is or it has. Contractions can also contribute to an overly informal tone. ...

New IBM guidance:

> Contractions are permitted in all types of content. Decide whether they fit the context. Follow these guidelines when you use contractions: ...

**Comment by ndeevy** [comment]
+1 to deviate from the ISG and recommend to disallow or at least avoid them. Removing them can increase readability, translation, and non-native reader comprehension in many cases and would help us maintain consistency with our current doc set.

**Comment by bergerhoffer** [comment]
Discussed at the 23 June council meeting. Decided that we should add guidance to avoid contractions in our normal technical docs (less conversational tone). For consistency in existing docs, for translation reasons, and for international audience reasons. But to allow flexibility for them if you're using a less formal tone (most conversational or fairly conversational), for example in quickstart content.

@bergerhoffer to draft a PR

**Comment by mportman12** [comment]
@bergerhoffer Can you create a PR for this issue?

**Comment by bergerhoffer** [comment]
Opened PR #93 with a draft of an entry.

**Comment by bergerhoffer** [comment]
Closing, as #93 was merged.
