### ISSUE TITLE
Conscious language replacement for blacklist/whitelist

### ISSUE THREAD

**Issue by ndeevy** [redhat-documentation/supplementary-style-guide#88]
Internally within RH we offer some flexibility to replace problematic terms and increase inclusive/conscious language. Apparently, this is to accommodate upstream communities' needs and choices.

However, for  blacklist/white list, the Conscious Language Project group have agreed to promote this replacement: blocklist / allowlist , which is in line with the ISG. 
"blocklist / allowlist - this combination is recommended by the IBM Style Guide and should be used in absence of other considerations"

Speaking with Kartik and Sam about it, we thought an entry for this might be a good idea. Something that tells writers that for consistency, we should use the ISG-recommended option of blocklist / allowlist even though RH has allowed flexibility to replace such terms.

What do you think? 

 For more information about the Red Hat stance, search for [1] on the Source.
[1] Conscious Language Project: FAQ

**Comment by roldanbob** [comment]
Of course, we have to recognize differences due to our need to reflect in-product terminology. Our Engineering team was among the first to eliminate problematic language, and as I mentioned in an earlier thread, they renamed properties to use `[include|exclude]-list`.

**Comment by igkioka** [comment]
Thanks, Naomi! Have such CLP elements in the ISG would be helpful to keep consistency in our docs. Occurrences dependent on the code are flexible according to the product terminology needs.

**Comment by bergerhoffer** [comment]
Discussed at the 23 June style council meeting. Agreed that it would be good to add guidance to the SSG, though there was discussion about whether allowlist/blocklist really were the best terms, or if it would be better paired as allowlist/denylist.

We also want to add some guidance to recommend writing around the terms when possible (instead of just doing a find/replace of the terms).

Next steps were to open a PR with the conscious language guidance, providing the alternatives if your upstream communities chose a different alternative pairing, and the guidance to write around it. Then bring back to team for further discussion.

**Comment by spank50** [comment]
The discussion brought up a couple of points. One point is that "blocklist" sounds very much like "blacklist" depending upon the speaker. Another point is that we can choose better related antonyms. For example allow/deny  pass/block.  Block is not a well-related antonym for allow.

**Comment by mportman12** [comment]
@ndeevy Can you create a PR for this issue?

**Comment by mportman12** [comment]
@ndeevy Can you open a PR for this and add info on the conscious language committee's guidance and guidance on how to write around problem terms?

**Comment by bergerhoffer** [comment]
@ndeevy Any chance you'd have time for this sometime soon? This is coming up for the OpenShift team soon, so it would be nice to make sure that we're following what the SSG is going to recommend.

**Comment by ndeevy** [comment]
Thanks for the nudge @mportman12 and @bergerhoffer 
Please take a peek at the connected PR - please and thanks!

**Comment by ndeevy** [comment]
Closing because this issue is resolved by #109. Published:
https://redhat-documentation.github.io/supplementary-style-guide/#conscious-language
