### ISSUE TITLE
Use ${} format to represent user-replaced values (URVs) in XML snippets

### ISSUE THREAD

**Issue by dfitzmau** [redhat-documentation/supplementary-style-guide#94]
**Purpose**
I've raised this PR to track the use of the _${} format_ for XML elements (and possibly other code bases that specify elements with angle brackets (<>)). A discussion on the following PR has agreement  comments on the use of _${} format_ for XML snippets versus the use of angle brackets:

https://github.com/redhat-documentation/supplementary-style-guide/issues/25

**Issue**
On writing for the JBoss EAP product, I encountered the follow problem when I used the recommended angle brackets for URVs with XML elements:

`<principal_claim_key>>`

The final appended angle bracket relates to the XML element and not the URV. A user might intentionally delete the additional angle bracket due to its proximity to the URV after the code renders to an HTML format. Visually, the code snippet looks cluttered.

**Suggestion** 
Use the  _${} format_ for URVs in XML elements and for any other code bases that use angle brackets to represent open and closing tags. For example:

`<${spring-boot.version}>`

**Comment by bergerhoffer** [comment]
Opened #95 to add this entry.

**Comment by bergerhoffer** [comment]
Closing because the PR has merged. Update is live: https://redhat-documentation.github.io/supplementary-style-guide/#user-replaced-values-xml
